package dao.mybatis.mapper;

import dao.mybatis.model.Ads;
import dao.mybatis.model.AdsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ADS
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int countByExample(AdsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ADS
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int deleteByExample(AdsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ADS
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ADS
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int insert(Ads record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ADS
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int insertSelective(Ads record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ADS
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	List<Ads> selectByExample(AdsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ADS
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	Ads selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ADS
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByExampleSelective(@Param("record") Ads record,
			@Param("example") AdsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ADS
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByExample(@Param("record") Ads record,
			@Param("example") AdsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ADS
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByPrimaryKeySelective(Ads record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ADS
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByPrimaryKey(Ads record);
}