package dao.mybatis.mapper;

import dao.mybatis.model.Ordermx;
import dao.mybatis.model.OrdermxExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrdermxMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ORDERMX
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int countByExample(OrdermxExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ORDERMX
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int deleteByExample(OrdermxExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ORDERMX
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ORDERMX
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int insert(Ordermx record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ORDERMX
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int insertSelective(Ordermx record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ORDERMX
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	List<Ordermx> selectByExample(OrdermxExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ORDERMX
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	Ordermx selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ORDERMX
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByExampleSelective(@Param("record") Ordermx record,
			@Param("example") OrdermxExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ORDERMX
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByExample(@Param("record") Ordermx record,
			@Param("example") OrdermxExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ORDERMX
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByPrimaryKeySelective(Ordermx record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ORDERMX
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByPrimaryKey(Ordermx record);
}