package dao.mybatis.mapper;

import dao.mybatis.model.Permission;
import dao.mybatis.model.PermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PermissionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int countByExample(PermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int deleteByExample(PermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int deleteByPrimaryKey(String permissionDm);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int insert(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int insertSelective(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	List<Permission> selectByExample(PermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	Permission selectByPrimaryKey(String permissionDm);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByExampleSelective(@Param("record") Permission record,
			@Param("example") PermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByExample(@Param("record") Permission record,
			@Param("example") PermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByPrimaryKeySelective(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByPrimaryKey(Permission record);
}