package dao.mybatis.mapper;

import dao.mybatis.model.Role;
import dao.mybatis.model.RoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int countByExample(RoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int deleteByExample(RoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int deleteByPrimaryKey(String roleDm);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int insert(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int insertSelective(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	List<Role> selectByExample(RoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	Role selectByPrimaryKey(String roleDm);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByExampleSelective(@Param("record") Role record,
			@Param("example") RoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByExample(@Param("record") Role record,
			@Param("example") RoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByPrimaryKeySelective(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByPrimaryKey(Role record);
}