package dao.mybatis.mapper;

import dao.mybatis.model.Role_permission;
import dao.mybatis.model.Role_permissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Role_permissionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE_PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int countByExample(Role_permissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE_PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int deleteByExample(Role_permissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE_PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE_PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int insert(Role_permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE_PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int insertSelective(Role_permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE_PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	List<Role_permission> selectByExample(Role_permissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE_PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	Role_permission selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE_PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByExampleSelective(@Param("record") Role_permission record,
			@Param("example") Role_permissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE_PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByExample(@Param("record") Role_permission record,
			@Param("example") Role_permissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE_PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByPrimaryKeySelective(Role_permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE_PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByPrimaryKey(Role_permission record);
}