package dao.mybatis.mapper;

import dao.mybatis.model.Stru;
import dao.mybatis.model.StruExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StruMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.STRU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int countByExample(StruExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.STRU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int deleteByExample(StruExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.STRU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int deleteByPrimaryKey(String jgDm);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.STRU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int insert(Stru record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.STRU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int insertSelective(Stru record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.STRU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	List<Stru> selectByExample(StruExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.STRU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	Stru selectByPrimaryKey(String jgDm);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.STRU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByExampleSelective(@Param("record") Stru record,
			@Param("example") StruExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.STRU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByExample(@Param("record") Stru record,
			@Param("example") StruExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.STRU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByPrimaryKeySelective(Stru record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.STRU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByPrimaryKey(Stru record);
}