package dao.mybatis.mapper;

import dao.mybatis.model.User_role;
import dao.mybatis.model.User_roleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface User_roleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USER_ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int countByExample(User_roleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USER_ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int deleteByExample(User_roleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USER_ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USER_ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int insert(User_role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USER_ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int insertSelective(User_role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USER_ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	List<User_role> selectByExample(User_roleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USER_ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	User_role selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USER_ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByExampleSelective(@Param("record") User_role record,
			@Param("example") User_roleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USER_ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByExample(@Param("record") User_role record,
			@Param("example") User_roleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USER_ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByPrimaryKeySelective(User_role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USER_ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByPrimaryKey(User_role record);
}