package dao.mybatis.mapper;

import dao.mybatis.model.User;
import dao.mybatis.model.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USERS
	 * @mbggenerated  Thu Nov 26 13:38:43 CAT 2015
	 */
	int countByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USERS
	 * @mbggenerated  Thu Nov 26 13:38:43 CAT 2015
	 */
	int deleteByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USERS
	 * @mbggenerated  Thu Nov 26 13:38:43 CAT 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USERS
	 * @mbggenerated  Thu Nov 26 13:38:43 CAT 2015
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USERS
	 * @mbggenerated  Thu Nov 26 13:38:43 CAT 2015
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USERS
	 * @mbggenerated  Thu Nov 26 13:38:43 CAT 2015
	 */
	List<User> selectByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USERS
	 * @mbggenerated  Thu Nov 26 13:38:43 CAT 2015
	 */
	User selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USERS
	 * @mbggenerated  Thu Nov 26 13:38:43 CAT 2015
	 */
	int updateByExampleSelective(@Param("record") User record,
			@Param("example") UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USERS
	 * @mbggenerated  Thu Nov 26 13:38:43 CAT 2015
	 */
	int updateByExample(@Param("record") User record,
			@Param("example") UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USERS
	 * @mbggenerated  Thu Nov 26 13:38:43 CAT 2015
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USERS
	 * @mbggenerated  Thu Nov 26 13:38:43 CAT 2015
	 */
	int updateByPrimaryKey(User record);
}