package dao.mybatis.mapper;

import dao.mybatis.model.Vip;
import dao.mybatis.model.VipExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VipMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.VIP
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int countByExample(VipExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.VIP
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int deleteByExample(VipExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.VIP
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.VIP
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int insert(Vip record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.VIP
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int insertSelective(Vip record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.VIP
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	List<Vip> selectByExample(VipExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.VIP
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	Vip selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.VIP
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByExampleSelective(@Param("record") Vip record,
			@Param("example") VipExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.VIP
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByExample(@Param("record") Vip record,
			@Param("example") VipExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.VIP
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByPrimaryKeySelective(Vip record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.VIP
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	int updateByPrimaryKey(Vip record);
}