package dao.mybatis.model;

import java.util.Date;

public class Ads {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.ADS.ID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.ADS.MC
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String mc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.ADS.USERID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.ADS.URL
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.ADS.PHOTO
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String photo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.ADS.BEGINTIME
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private Date begintime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.ADS.ENDTIME
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private Date endtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.ADS.ISUSE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String isuse;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.ADS.ID
	 * @return  the value of RESTAURANT.ADS.ID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.ADS.ID
	 * @param id  the value for RESTAURANT.ADS.ID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.ADS.MC
	 * @return  the value of RESTAURANT.ADS.MC
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getMc() {
		return mc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.ADS.MC
	 * @param mc  the value for RESTAURANT.ADS.MC
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setMc(String mc) {
		this.mc = mc == null ? null : mc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.ADS.USERID
	 * @return  the value of RESTAURANT.ADS.USERID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.ADS.USERID
	 * @param userid  the value for RESTAURANT.ADS.USERID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setUserid(String userid) {
		this.userid = userid == null ? null : userid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.ADS.URL
	 * @return  the value of RESTAURANT.ADS.URL
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.ADS.URL
	 * @param url  the value for RESTAURANT.ADS.URL
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.ADS.PHOTO
	 * @return  the value of RESTAURANT.ADS.PHOTO
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getPhoto() {
		return photo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.ADS.PHOTO
	 * @param photo  the value for RESTAURANT.ADS.PHOTO
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setPhoto(String photo) {
		this.photo = photo == null ? null : photo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.ADS.BEGINTIME
	 * @return  the value of RESTAURANT.ADS.BEGINTIME
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public Date getBegintime() {
		return begintime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.ADS.BEGINTIME
	 * @param begintime  the value for RESTAURANT.ADS.BEGINTIME
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setBegintime(Date begintime) {
		this.begintime = begintime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.ADS.ENDTIME
	 * @return  the value of RESTAURANT.ADS.ENDTIME
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public Date getEndtime() {
		return endtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.ADS.ENDTIME
	 * @param endtime  the value for RESTAURANT.ADS.ENDTIME
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.ADS.ISUSE
	 * @return  the value of RESTAURANT.ADS.ISUSE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getIsuse() {
		return isuse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.ADS.ISUSE
	 * @param isuse  the value for RESTAURANT.ADS.ISUSE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setIsuse(String isuse) {
		this.isuse = isuse == null ? null : isuse.trim();
	}
}