package dao.mybatis.model;

import java.util.Date;

public class News {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.NEWS.ID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.NEWS.TITLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.NEWS.CONTENT
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.NEWS.AUTHOR
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String author;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.NEWS.CREATETIME
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.NEWS.ALERTUSER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String alertuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.NEWS.ALERTTIME
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private Date alerttime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.NEWS.ISUSE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String isuse;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.NEWS.FUJIAN_MC
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String fujianMc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.NEWS.FUJIAN_URL
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String fujianUrl;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.NEWS.ID
	 * @return  the value of RESTAURANT.NEWS.ID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.NEWS.ID
	 * @param id  the value for RESTAURANT.NEWS.ID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.NEWS.TITLE
	 * @return  the value of RESTAURANT.NEWS.TITLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.NEWS.TITLE
	 * @param title  the value for RESTAURANT.NEWS.TITLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.NEWS.CONTENT
	 * @return  the value of RESTAURANT.NEWS.CONTENT
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.NEWS.CONTENT
	 * @param content  the value for RESTAURANT.NEWS.CONTENT
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.NEWS.AUTHOR
	 * @return  the value of RESTAURANT.NEWS.AUTHOR
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.NEWS.AUTHOR
	 * @param author  the value for RESTAURANT.NEWS.AUTHOR
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setAuthor(String author) {
		this.author = author == null ? null : author.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.NEWS.CREATETIME
	 * @return  the value of RESTAURANT.NEWS.CREATETIME
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.NEWS.CREATETIME
	 * @param createtime  the value for RESTAURANT.NEWS.CREATETIME
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.NEWS.ALERTUSER
	 * @return  the value of RESTAURANT.NEWS.ALERTUSER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getAlertuser() {
		return alertuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.NEWS.ALERTUSER
	 * @param alertuser  the value for RESTAURANT.NEWS.ALERTUSER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setAlertuser(String alertuser) {
		this.alertuser = alertuser == null ? null : alertuser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.NEWS.ALERTTIME
	 * @return  the value of RESTAURANT.NEWS.ALERTTIME
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public Date getAlerttime() {
		return alerttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.NEWS.ALERTTIME
	 * @param alerttime  the value for RESTAURANT.NEWS.ALERTTIME
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setAlerttime(Date alerttime) {
		this.alerttime = alerttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.NEWS.ISUSE
	 * @return  the value of RESTAURANT.NEWS.ISUSE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getIsuse() {
		return isuse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.NEWS.ISUSE
	 * @param isuse  the value for RESTAURANT.NEWS.ISUSE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setIsuse(String isuse) {
		this.isuse = isuse == null ? null : isuse.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.NEWS.FUJIAN_MC
	 * @return  the value of RESTAURANT.NEWS.FUJIAN_MC
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getFujianMc() {
		return fujianMc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.NEWS.FUJIAN_MC
	 * @param fujianMc  the value for RESTAURANT.NEWS.FUJIAN_MC
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setFujianMc(String fujianMc) {
		this.fujianMc = fujianMc == null ? null : fujianMc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.NEWS.FUJIAN_URL
	 * @return  the value of RESTAURANT.NEWS.FUJIAN_URL
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getFujianUrl() {
		return fujianUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.NEWS.FUJIAN_URL
	 * @param fujianUrl  the value for RESTAURANT.NEWS.FUJIAN_URL
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setFujianUrl(String fujianUrl) {
		this.fujianUrl = fujianUrl == null ? null : fujianUrl.trim();
	}
}