package dao.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class NewsExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RESTAURANT.NEWS
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RESTAURANT.NEWS
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RESTAURANT.NEWS
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.NEWS
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public NewsExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.NEWS
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.NEWS
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.NEWS
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.NEWS
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.NEWS
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.NEWS
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.NEWS
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.NEWS
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.NEWS
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.NEWS
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table RESTAURANT.NEWS
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("TITLE is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("TITLE is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("TITLE =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("TITLE <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("TITLE >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("TITLE >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("TITLE <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("TITLE <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("TITLE like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("TITLE not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("TITLE in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("TITLE not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("TITLE between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("TITLE not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andContentIsNull() {
			addCriterion("CONTENT is null");
			return (Criteria) this;
		}

		public Criteria andContentIsNotNull() {
			addCriterion("CONTENT is not null");
			return (Criteria) this;
		}

		public Criteria andContentEqualTo(String value) {
			addCriterion("CONTENT =", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotEqualTo(String value) {
			addCriterion("CONTENT <>", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThan(String value) {
			addCriterion("CONTENT >", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThanOrEqualTo(String value) {
			addCriterion("CONTENT >=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThan(String value) {
			addCriterion("CONTENT <", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThanOrEqualTo(String value) {
			addCriterion("CONTENT <=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLike(String value) {
			addCriterion("CONTENT like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotLike(String value) {
			addCriterion("CONTENT not like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentIn(List<String> values) {
			addCriterion("CONTENT in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotIn(List<String> values) {
			addCriterion("CONTENT not in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentBetween(String value1, String value2) {
			addCriterion("CONTENT between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotBetween(String value1, String value2) {
			addCriterion("CONTENT not between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andAuthorIsNull() {
			addCriterion("AUTHOR is null");
			return (Criteria) this;
		}

		public Criteria andAuthorIsNotNull() {
			addCriterion("AUTHOR is not null");
			return (Criteria) this;
		}

		public Criteria andAuthorEqualTo(String value) {
			addCriterion("AUTHOR =", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorNotEqualTo(String value) {
			addCriterion("AUTHOR <>", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorGreaterThan(String value) {
			addCriterion("AUTHOR >", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorGreaterThanOrEqualTo(String value) {
			addCriterion("AUTHOR >=", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorLessThan(String value) {
			addCriterion("AUTHOR <", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorLessThanOrEqualTo(String value) {
			addCriterion("AUTHOR <=", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorLike(String value) {
			addCriterion("AUTHOR like", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorNotLike(String value) {
			addCriterion("AUTHOR not like", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorIn(List<String> values) {
			addCriterion("AUTHOR in", values, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorNotIn(List<String> values) {
			addCriterion("AUTHOR not in", values, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorBetween(String value1, String value2) {
			addCriterion("AUTHOR between", value1, value2, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorNotBetween(String value1, String value2) {
			addCriterion("AUTHOR not between", value1, value2, "author");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNull() {
			addCriterion("CREATETIME is null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNotNull() {
			addCriterion("CREATETIME is not null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeEqualTo(Date value) {
			addCriterionForJDBCDate("CREATETIME =", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("CREATETIME <>", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThan(Date value) {
			addCriterionForJDBCDate("CREATETIME >", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATETIME >=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThan(Date value) {
			addCriterionForJDBCDate("CREATETIME <", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATETIME <=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIn(List<Date> values) {
			addCriterionForJDBCDate("CREATETIME in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("CREATETIME not in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATETIME between", value1, value2,
					"createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATETIME not between", value1, value2,
					"createtime");
			return (Criteria) this;
		}

		public Criteria andAlertuserIsNull() {
			addCriterion("ALERTUSER is null");
			return (Criteria) this;
		}

		public Criteria andAlertuserIsNotNull() {
			addCriterion("ALERTUSER is not null");
			return (Criteria) this;
		}

		public Criteria andAlertuserEqualTo(String value) {
			addCriterion("ALERTUSER =", value, "alertuser");
			return (Criteria) this;
		}

		public Criteria andAlertuserNotEqualTo(String value) {
			addCriterion("ALERTUSER <>", value, "alertuser");
			return (Criteria) this;
		}

		public Criteria andAlertuserGreaterThan(String value) {
			addCriterion("ALERTUSER >", value, "alertuser");
			return (Criteria) this;
		}

		public Criteria andAlertuserGreaterThanOrEqualTo(String value) {
			addCriterion("ALERTUSER >=", value, "alertuser");
			return (Criteria) this;
		}

		public Criteria andAlertuserLessThan(String value) {
			addCriterion("ALERTUSER <", value, "alertuser");
			return (Criteria) this;
		}

		public Criteria andAlertuserLessThanOrEqualTo(String value) {
			addCriterion("ALERTUSER <=", value, "alertuser");
			return (Criteria) this;
		}

		public Criteria andAlertuserLike(String value) {
			addCriterion("ALERTUSER like", value, "alertuser");
			return (Criteria) this;
		}

		public Criteria andAlertuserNotLike(String value) {
			addCriterion("ALERTUSER not like", value, "alertuser");
			return (Criteria) this;
		}

		public Criteria andAlertuserIn(List<String> values) {
			addCriterion("ALERTUSER in", values, "alertuser");
			return (Criteria) this;
		}

		public Criteria andAlertuserNotIn(List<String> values) {
			addCriterion("ALERTUSER not in", values, "alertuser");
			return (Criteria) this;
		}

		public Criteria andAlertuserBetween(String value1, String value2) {
			addCriterion("ALERTUSER between", value1, value2, "alertuser");
			return (Criteria) this;
		}

		public Criteria andAlertuserNotBetween(String value1, String value2) {
			addCriterion("ALERTUSER not between", value1, value2, "alertuser");
			return (Criteria) this;
		}

		public Criteria andAlerttimeIsNull() {
			addCriterion("ALERTTIME is null");
			return (Criteria) this;
		}

		public Criteria andAlerttimeIsNotNull() {
			addCriterion("ALERTTIME is not null");
			return (Criteria) this;
		}

		public Criteria andAlerttimeEqualTo(Date value) {
			addCriterionForJDBCDate("ALERTTIME =", value, "alerttime");
			return (Criteria) this;
		}

		public Criteria andAlerttimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("ALERTTIME <>", value, "alerttime");
			return (Criteria) this;
		}

		public Criteria andAlerttimeGreaterThan(Date value) {
			addCriterionForJDBCDate("ALERTTIME >", value, "alerttime");
			return (Criteria) this;
		}

		public Criteria andAlerttimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ALERTTIME >=", value, "alerttime");
			return (Criteria) this;
		}

		public Criteria andAlerttimeLessThan(Date value) {
			addCriterionForJDBCDate("ALERTTIME <", value, "alerttime");
			return (Criteria) this;
		}

		public Criteria andAlerttimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ALERTTIME <=", value, "alerttime");
			return (Criteria) this;
		}

		public Criteria andAlerttimeIn(List<Date> values) {
			addCriterionForJDBCDate("ALERTTIME in", values, "alerttime");
			return (Criteria) this;
		}

		public Criteria andAlerttimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("ALERTTIME not in", values, "alerttime");
			return (Criteria) this;
		}

		public Criteria andAlerttimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ALERTTIME between", value1, value2,
					"alerttime");
			return (Criteria) this;
		}

		public Criteria andAlerttimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ALERTTIME not between", value1, value2,
					"alerttime");
			return (Criteria) this;
		}

		public Criteria andIsuseIsNull() {
			addCriterion("ISUSE is null");
			return (Criteria) this;
		}

		public Criteria andIsuseIsNotNull() {
			addCriterion("ISUSE is not null");
			return (Criteria) this;
		}

		public Criteria andIsuseEqualTo(String value) {
			addCriterion("ISUSE =", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseNotEqualTo(String value) {
			addCriterion("ISUSE <>", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseGreaterThan(String value) {
			addCriterion("ISUSE >", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseGreaterThanOrEqualTo(String value) {
			addCriterion("ISUSE >=", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseLessThan(String value) {
			addCriterion("ISUSE <", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseLessThanOrEqualTo(String value) {
			addCriterion("ISUSE <=", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseLike(String value) {
			addCriterion("ISUSE like", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseNotLike(String value) {
			addCriterion("ISUSE not like", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseIn(List<String> values) {
			addCriterion("ISUSE in", values, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseNotIn(List<String> values) {
			addCriterion("ISUSE not in", values, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseBetween(String value1, String value2) {
			addCriterion("ISUSE between", value1, value2, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseNotBetween(String value1, String value2) {
			addCriterion("ISUSE not between", value1, value2, "isuse");
			return (Criteria) this;
		}

		public Criteria andFujianMcIsNull() {
			addCriterion("FUJIAN_MC is null");
			return (Criteria) this;
		}

		public Criteria andFujianMcIsNotNull() {
			addCriterion("FUJIAN_MC is not null");
			return (Criteria) this;
		}

		public Criteria andFujianMcEqualTo(String value) {
			addCriterion("FUJIAN_MC =", value, "fujianMc");
			return (Criteria) this;
		}

		public Criteria andFujianMcNotEqualTo(String value) {
			addCriterion("FUJIAN_MC <>", value, "fujianMc");
			return (Criteria) this;
		}

		public Criteria andFujianMcGreaterThan(String value) {
			addCriterion("FUJIAN_MC >", value, "fujianMc");
			return (Criteria) this;
		}

		public Criteria andFujianMcGreaterThanOrEqualTo(String value) {
			addCriterion("FUJIAN_MC >=", value, "fujianMc");
			return (Criteria) this;
		}

		public Criteria andFujianMcLessThan(String value) {
			addCriterion("FUJIAN_MC <", value, "fujianMc");
			return (Criteria) this;
		}

		public Criteria andFujianMcLessThanOrEqualTo(String value) {
			addCriterion("FUJIAN_MC <=", value, "fujianMc");
			return (Criteria) this;
		}

		public Criteria andFujianMcLike(String value) {
			addCriterion("FUJIAN_MC like", value, "fujianMc");
			return (Criteria) this;
		}

		public Criteria andFujianMcNotLike(String value) {
			addCriterion("FUJIAN_MC not like", value, "fujianMc");
			return (Criteria) this;
		}

		public Criteria andFujianMcIn(List<String> values) {
			addCriterion("FUJIAN_MC in", values, "fujianMc");
			return (Criteria) this;
		}

		public Criteria andFujianMcNotIn(List<String> values) {
			addCriterion("FUJIAN_MC not in", values, "fujianMc");
			return (Criteria) this;
		}

		public Criteria andFujianMcBetween(String value1, String value2) {
			addCriterion("FUJIAN_MC between", value1, value2, "fujianMc");
			return (Criteria) this;
		}

		public Criteria andFujianMcNotBetween(String value1, String value2) {
			addCriterion("FUJIAN_MC not between", value1, value2, "fujianMc");
			return (Criteria) this;
		}

		public Criteria andFujianUrlIsNull() {
			addCriterion("FUJIAN_URL is null");
			return (Criteria) this;
		}

		public Criteria andFujianUrlIsNotNull() {
			addCriterion("FUJIAN_URL is not null");
			return (Criteria) this;
		}

		public Criteria andFujianUrlEqualTo(String value) {
			addCriterion("FUJIAN_URL =", value, "fujianUrl");
			return (Criteria) this;
		}

		public Criteria andFujianUrlNotEqualTo(String value) {
			addCriterion("FUJIAN_URL <>", value, "fujianUrl");
			return (Criteria) this;
		}

		public Criteria andFujianUrlGreaterThan(String value) {
			addCriterion("FUJIAN_URL >", value, "fujianUrl");
			return (Criteria) this;
		}

		public Criteria andFujianUrlGreaterThanOrEqualTo(String value) {
			addCriterion("FUJIAN_URL >=", value, "fujianUrl");
			return (Criteria) this;
		}

		public Criteria andFujianUrlLessThan(String value) {
			addCriterion("FUJIAN_URL <", value, "fujianUrl");
			return (Criteria) this;
		}

		public Criteria andFujianUrlLessThanOrEqualTo(String value) {
			addCriterion("FUJIAN_URL <=", value, "fujianUrl");
			return (Criteria) this;
		}

		public Criteria andFujianUrlLike(String value) {
			addCriterion("FUJIAN_URL like", value, "fujianUrl");
			return (Criteria) this;
		}

		public Criteria andFujianUrlNotLike(String value) {
			addCriterion("FUJIAN_URL not like", value, "fujianUrl");
			return (Criteria) this;
		}

		public Criteria andFujianUrlIn(List<String> values) {
			addCriterion("FUJIAN_URL in", values, "fujianUrl");
			return (Criteria) this;
		}

		public Criteria andFujianUrlNotIn(List<String> values) {
			addCriterion("FUJIAN_URL not in", values, "fujianUrl");
			return (Criteria) this;
		}

		public Criteria andFujianUrlBetween(String value1, String value2) {
			addCriterion("FUJIAN_URL between", value1, value2, "fujianUrl");
			return (Criteria) this;
		}

		public Criteria andFujianUrlNotBetween(String value1, String value2) {
			addCriterion("FUJIAN_URL not between", value1, value2, "fujianUrl");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table RESTAURANT.NEWS
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table news
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 26 10:37:30 CAT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}