package dao.mybatis.model;

public class Ordermx {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.ORDERMX.ID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.ORDERMX.ORDERID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String orderid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.ORDERMX.PRODUCTID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String productid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.ORDERMX.STATE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String state;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.ORDERMX.ID
	 * @return  the value of RESTAURANT.ORDERMX.ID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.ORDERMX.ID
	 * @param id  the value for RESTAURANT.ORDERMX.ID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.ORDERMX.ORDERID
	 * @return  the value of RESTAURANT.ORDERMX.ORDERID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getOrderid() {
		return orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.ORDERMX.ORDERID
	 * @param orderid  the value for RESTAURANT.ORDERMX.ORDERID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setOrderid(String orderid) {
		this.orderid = orderid == null ? null : orderid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.ORDERMX.PRODUCTID
	 * @return  the value of RESTAURANT.ORDERMX.PRODUCTID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getProductid() {
		return productid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.ORDERMX.PRODUCTID
	 * @param productid  the value for RESTAURANT.ORDERMX.PRODUCTID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setProductid(String productid) {
		this.productid = productid == null ? null : productid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.ORDERMX.STATE
	 * @return  the value of RESTAURANT.ORDERMX.STATE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.ORDERMX.STATE
	 * @param state  the value for RESTAURANT.ORDERMX.STATE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setState(String state) {
		this.state = state == null ? null : state.trim();
	}
}