package dao.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class PermissionExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RESTAURANT.PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RESTAURANT.PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RESTAURANT.PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public PermissionExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table RESTAURANT.PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andPermissionDmIsNull() {
			addCriterion("PERMISSION_DM is null");
			return (Criteria) this;
		}

		public Criteria andPermissionDmIsNotNull() {
			addCriterion("PERMISSION_DM is not null");
			return (Criteria) this;
		}

		public Criteria andPermissionDmEqualTo(String value) {
			addCriterion("PERMISSION_DM =", value, "permissionDm");
			return (Criteria) this;
		}

		public Criteria andPermissionDmNotEqualTo(String value) {
			addCriterion("PERMISSION_DM <>", value, "permissionDm");
			return (Criteria) this;
		}

		public Criteria andPermissionDmGreaterThan(String value) {
			addCriterion("PERMISSION_DM >", value, "permissionDm");
			return (Criteria) this;
		}

		public Criteria andPermissionDmGreaterThanOrEqualTo(String value) {
			addCriterion("PERMISSION_DM >=", value, "permissionDm");
			return (Criteria) this;
		}

		public Criteria andPermissionDmLessThan(String value) {
			addCriterion("PERMISSION_DM <", value, "permissionDm");
			return (Criteria) this;
		}

		public Criteria andPermissionDmLessThanOrEqualTo(String value) {
			addCriterion("PERMISSION_DM <=", value, "permissionDm");
			return (Criteria) this;
		}

		public Criteria andPermissionDmLike(String value) {
			addCriterion("PERMISSION_DM like", value, "permissionDm");
			return (Criteria) this;
		}

		public Criteria andPermissionDmNotLike(String value) {
			addCriterion("PERMISSION_DM not like", value, "permissionDm");
			return (Criteria) this;
		}

		public Criteria andPermissionDmIn(List<String> values) {
			addCriterion("PERMISSION_DM in", values, "permissionDm");
			return (Criteria) this;
		}

		public Criteria andPermissionDmNotIn(List<String> values) {
			addCriterion("PERMISSION_DM not in", values, "permissionDm");
			return (Criteria) this;
		}

		public Criteria andPermissionDmBetween(String value1, String value2) {
			addCriterion("PERMISSION_DM between", value1, value2,
					"permissionDm");
			return (Criteria) this;
		}

		public Criteria andPermissionDmNotBetween(String value1, String value2) {
			addCriterion("PERMISSION_DM not between", value1, value2,
					"permissionDm");
			return (Criteria) this;
		}

		public Criteria andPermissionMcIsNull() {
			addCriterion("PERMISSION_MC is null");
			return (Criteria) this;
		}

		public Criteria andPermissionMcIsNotNull() {
			addCriterion("PERMISSION_MC is not null");
			return (Criteria) this;
		}

		public Criteria andPermissionMcEqualTo(String value) {
			addCriterion("PERMISSION_MC =", value, "permissionMc");
			return (Criteria) this;
		}

		public Criteria andPermissionMcNotEqualTo(String value) {
			addCriterion("PERMISSION_MC <>", value, "permissionMc");
			return (Criteria) this;
		}

		public Criteria andPermissionMcGreaterThan(String value) {
			addCriterion("PERMISSION_MC >", value, "permissionMc");
			return (Criteria) this;
		}

		public Criteria andPermissionMcGreaterThanOrEqualTo(String value) {
			addCriterion("PERMISSION_MC >=", value, "permissionMc");
			return (Criteria) this;
		}

		public Criteria andPermissionMcLessThan(String value) {
			addCriterion("PERMISSION_MC <", value, "permissionMc");
			return (Criteria) this;
		}

		public Criteria andPermissionMcLessThanOrEqualTo(String value) {
			addCriterion("PERMISSION_MC <=", value, "permissionMc");
			return (Criteria) this;
		}

		public Criteria andPermissionMcLike(String value) {
			addCriterion("PERMISSION_MC like", value, "permissionMc");
			return (Criteria) this;
		}

		public Criteria andPermissionMcNotLike(String value) {
			addCriterion("PERMISSION_MC not like", value, "permissionMc");
			return (Criteria) this;
		}

		public Criteria andPermissionMcIn(List<String> values) {
			addCriterion("PERMISSION_MC in", values, "permissionMc");
			return (Criteria) this;
		}

		public Criteria andPermissionMcNotIn(List<String> values) {
			addCriterion("PERMISSION_MC not in", values, "permissionMc");
			return (Criteria) this;
		}

		public Criteria andPermissionMcBetween(String value1, String value2) {
			addCriterion("PERMISSION_MC between", value1, value2,
					"permissionMc");
			return (Criteria) this;
		}

		public Criteria andPermissionMcNotBetween(String value1, String value2) {
			addCriterion("PERMISSION_MC not between", value1, value2,
					"permissionMc");
			return (Criteria) this;
		}

		public Criteria andUrlIsNull() {
			addCriterion("URL is null");
			return (Criteria) this;
		}

		public Criteria andUrlIsNotNull() {
			addCriterion("URL is not null");
			return (Criteria) this;
		}

		public Criteria andUrlEqualTo(String value) {
			addCriterion("URL =", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotEqualTo(String value) {
			addCriterion("URL <>", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlGreaterThan(String value) {
			addCriterion("URL >", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlGreaterThanOrEqualTo(String value) {
			addCriterion("URL >=", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLessThan(String value) {
			addCriterion("URL <", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLessThanOrEqualTo(String value) {
			addCriterion("URL <=", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLike(String value) {
			addCriterion("URL like", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotLike(String value) {
			addCriterion("URL not like", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlIn(List<String> values) {
			addCriterion("URL in", values, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotIn(List<String> values) {
			addCriterion("URL not in", values, "url");
			return (Criteria) this;
		}

		public Criteria andUrlBetween(String value1, String value2) {
			addCriterion("URL between", value1, value2, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotBetween(String value1, String value2) {
			addCriterion("URL not between", value1, value2, "url");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("CREATE_DATE is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("CREATE_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_DATE =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_DATE <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterionForJDBCDate("CREATE_DATE >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_DATE >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterionForJDBCDate("CREATE_DATE <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_DATE <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterionForJDBCDate("CREATE_DATE in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("CREATE_DATE not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATE_DATE between", value1, value2,
					"createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATE_DATE not between", value1, value2,
					"createDate");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNull() {
			addCriterion("CREATE_USER is null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNotNull() {
			addCriterion("CREATE_USER is not null");
			return (Criteria) this;
		}

		public Criteria andCreateUserEqualTo(String value) {
			addCriterion("CREATE_USER =", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotEqualTo(String value) {
			addCriterion("CREATE_USER <>", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThan(String value) {
			addCriterion("CREATE_USER >", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
			addCriterion("CREATE_USER >=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThan(String value) {
			addCriterion("CREATE_USER <", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThanOrEqualTo(String value) {
			addCriterion("CREATE_USER <=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLike(String value) {
			addCriterion("CREATE_USER like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotLike(String value) {
			addCriterion("CREATE_USER not like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserIn(List<String> values) {
			addCriterion("CREATE_USER in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotIn(List<String> values) {
			addCriterion("CREATE_USER not in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserBetween(String value1, String value2) {
			addCriterion("CREATE_USER between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotBetween(String value1, String value2) {
			addCriterion("CREATE_USER not between", value1, value2,
					"createUser");
			return (Criteria) this;
		}

		public Criteria andDescribesIsNull() {
			addCriterion("DESCRIBES is null");
			return (Criteria) this;
		}

		public Criteria andDescribesIsNotNull() {
			addCriterion("DESCRIBES is not null");
			return (Criteria) this;
		}

		public Criteria andDescribesEqualTo(String value) {
			addCriterion("DESCRIBES =", value, "describes");
			return (Criteria) this;
		}

		public Criteria andDescribesNotEqualTo(String value) {
			addCriterion("DESCRIBES <>", value, "describes");
			return (Criteria) this;
		}

		public Criteria andDescribesGreaterThan(String value) {
			addCriterion("DESCRIBES >", value, "describes");
			return (Criteria) this;
		}

		public Criteria andDescribesGreaterThanOrEqualTo(String value) {
			addCriterion("DESCRIBES >=", value, "describes");
			return (Criteria) this;
		}

		public Criteria andDescribesLessThan(String value) {
			addCriterion("DESCRIBES <", value, "describes");
			return (Criteria) this;
		}

		public Criteria andDescribesLessThanOrEqualTo(String value) {
			addCriterion("DESCRIBES <=", value, "describes");
			return (Criteria) this;
		}

		public Criteria andDescribesLike(String value) {
			addCriterion("DESCRIBES like", value, "describes");
			return (Criteria) this;
		}

		public Criteria andDescribesNotLike(String value) {
			addCriterion("DESCRIBES not like", value, "describes");
			return (Criteria) this;
		}

		public Criteria andDescribesIn(List<String> values) {
			addCriterion("DESCRIBES in", values, "describes");
			return (Criteria) this;
		}

		public Criteria andDescribesNotIn(List<String> values) {
			addCriterion("DESCRIBES not in", values, "describes");
			return (Criteria) this;
		}

		public Criteria andDescribesBetween(String value1, String value2) {
			addCriterion("DESCRIBES between", value1, value2, "describes");
			return (Criteria) this;
		}

		public Criteria andDescribesNotBetween(String value1, String value2) {
			addCriterion("DESCRIBES not between", value1, value2, "describes");
			return (Criteria) this;
		}

		public Criteria andBeizhuIsNull() {
			addCriterion("BEIZHU is null");
			return (Criteria) this;
		}

		public Criteria andBeizhuIsNotNull() {
			addCriterion("BEIZHU is not null");
			return (Criteria) this;
		}

		public Criteria andBeizhuEqualTo(String value) {
			addCriterion("BEIZHU =", value, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuNotEqualTo(String value) {
			addCriterion("BEIZHU <>", value, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuGreaterThan(String value) {
			addCriterion("BEIZHU >", value, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuGreaterThanOrEqualTo(String value) {
			addCriterion("BEIZHU >=", value, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuLessThan(String value) {
			addCriterion("BEIZHU <", value, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuLessThanOrEqualTo(String value) {
			addCriterion("BEIZHU <=", value, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuLike(String value) {
			addCriterion("BEIZHU like", value, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuNotLike(String value) {
			addCriterion("BEIZHU not like", value, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuIn(List<String> values) {
			addCriterion("BEIZHU in", values, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuNotIn(List<String> values) {
			addCriterion("BEIZHU not in", values, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuBetween(String value1, String value2) {
			addCriterion("BEIZHU between", value1, value2, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuNotBetween(String value1, String value2) {
			addCriterion("BEIZHU not between", value1, value2, "beizhu");
			return (Criteria) this;
		}

		public Criteria andAlertDateIsNull() {
			addCriterion("ALERT_DATE is null");
			return (Criteria) this;
		}

		public Criteria andAlertDateIsNotNull() {
			addCriterion("ALERT_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andAlertDateEqualTo(Date value) {
			addCriterionForJDBCDate("ALERT_DATE =", value, "alertDate");
			return (Criteria) this;
		}

		public Criteria andAlertDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("ALERT_DATE <>", value, "alertDate");
			return (Criteria) this;
		}

		public Criteria andAlertDateGreaterThan(Date value) {
			addCriterionForJDBCDate("ALERT_DATE >", value, "alertDate");
			return (Criteria) this;
		}

		public Criteria andAlertDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ALERT_DATE >=", value, "alertDate");
			return (Criteria) this;
		}

		public Criteria andAlertDateLessThan(Date value) {
			addCriterionForJDBCDate("ALERT_DATE <", value, "alertDate");
			return (Criteria) this;
		}

		public Criteria andAlertDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ALERT_DATE <=", value, "alertDate");
			return (Criteria) this;
		}

		public Criteria andAlertDateIn(List<Date> values) {
			addCriterionForJDBCDate("ALERT_DATE in", values, "alertDate");
			return (Criteria) this;
		}

		public Criteria andAlertDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("ALERT_DATE not in", values, "alertDate");
			return (Criteria) this;
		}

		public Criteria andAlertDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ALERT_DATE between", value1, value2,
					"alertDate");
			return (Criteria) this;
		}

		public Criteria andAlertDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ALERT_DATE not between", value1, value2,
					"alertDate");
			return (Criteria) this;
		}

		public Criteria andAlertUserIsNull() {
			addCriterion("ALERT_USER is null");
			return (Criteria) this;
		}

		public Criteria andAlertUserIsNotNull() {
			addCriterion("ALERT_USER is not null");
			return (Criteria) this;
		}

		public Criteria andAlertUserEqualTo(String value) {
			addCriterion("ALERT_USER =", value, "alertUser");
			return (Criteria) this;
		}

		public Criteria andAlertUserNotEqualTo(String value) {
			addCriterion("ALERT_USER <>", value, "alertUser");
			return (Criteria) this;
		}

		public Criteria andAlertUserGreaterThan(String value) {
			addCriterion("ALERT_USER >", value, "alertUser");
			return (Criteria) this;
		}

		public Criteria andAlertUserGreaterThanOrEqualTo(String value) {
			addCriterion("ALERT_USER >=", value, "alertUser");
			return (Criteria) this;
		}

		public Criteria andAlertUserLessThan(String value) {
			addCriterion("ALERT_USER <", value, "alertUser");
			return (Criteria) this;
		}

		public Criteria andAlertUserLessThanOrEqualTo(String value) {
			addCriterion("ALERT_USER <=", value, "alertUser");
			return (Criteria) this;
		}

		public Criteria andAlertUserLike(String value) {
			addCriterion("ALERT_USER like", value, "alertUser");
			return (Criteria) this;
		}

		public Criteria andAlertUserNotLike(String value) {
			addCriterion("ALERT_USER not like", value, "alertUser");
			return (Criteria) this;
		}

		public Criteria andAlertUserIn(List<String> values) {
			addCriterion("ALERT_USER in", values, "alertUser");
			return (Criteria) this;
		}

		public Criteria andAlertUserNotIn(List<String> values) {
			addCriterion("ALERT_USER not in", values, "alertUser");
			return (Criteria) this;
		}

		public Criteria andAlertUserBetween(String value1, String value2) {
			addCriterion("ALERT_USER between", value1, value2, "alertUser");
			return (Criteria) this;
		}

		public Criteria andAlertUserNotBetween(String value1, String value2) {
			addCriterion("ALERT_USER not between", value1, value2, "alertUser");
			return (Criteria) this;
		}

		public Criteria andIsuseIsNull() {
			addCriterion("ISUSE is null");
			return (Criteria) this;
		}

		public Criteria andIsuseIsNotNull() {
			addCriterion("ISUSE is not null");
			return (Criteria) this;
		}

		public Criteria andIsuseEqualTo(String value) {
			addCriterion("ISUSE =", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseNotEqualTo(String value) {
			addCriterion("ISUSE <>", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseGreaterThan(String value) {
			addCriterion("ISUSE >", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseGreaterThanOrEqualTo(String value) {
			addCriterion("ISUSE >=", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseLessThan(String value) {
			addCriterion("ISUSE <", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseLessThanOrEqualTo(String value) {
			addCriterion("ISUSE <=", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseLike(String value) {
			addCriterion("ISUSE like", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseNotLike(String value) {
			addCriterion("ISUSE not like", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseIn(List<String> values) {
			addCriterion("ISUSE in", values, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseNotIn(List<String> values) {
			addCriterion("ISUSE not in", values, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseBetween(String value1, String value2) {
			addCriterion("ISUSE between", value1, value2, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseNotBetween(String value1, String value2) {
			addCriterion("ISUSE not between", value1, value2, "isuse");
			return (Criteria) this;
		}

		public Criteria andParentcodeIsNull() {
			addCriterion("PARENTCODE is null");
			return (Criteria) this;
		}

		public Criteria andParentcodeIsNotNull() {
			addCriterion("PARENTCODE is not null");
			return (Criteria) this;
		}

		public Criteria andParentcodeEqualTo(String value) {
			addCriterion("PARENTCODE =", value, "parentcode");
			return (Criteria) this;
		}

		public Criteria andParentcodeNotEqualTo(String value) {
			addCriterion("PARENTCODE <>", value, "parentcode");
			return (Criteria) this;
		}

		public Criteria andParentcodeGreaterThan(String value) {
			addCriterion("PARENTCODE >", value, "parentcode");
			return (Criteria) this;
		}

		public Criteria andParentcodeGreaterThanOrEqualTo(String value) {
			addCriterion("PARENTCODE >=", value, "parentcode");
			return (Criteria) this;
		}

		public Criteria andParentcodeLessThan(String value) {
			addCriterion("PARENTCODE <", value, "parentcode");
			return (Criteria) this;
		}

		public Criteria andParentcodeLessThanOrEqualTo(String value) {
			addCriterion("PARENTCODE <=", value, "parentcode");
			return (Criteria) this;
		}

		public Criteria andParentcodeLike(String value) {
			addCriterion("PARENTCODE like", value, "parentcode");
			return (Criteria) this;
		}

		public Criteria andParentcodeNotLike(String value) {
			addCriterion("PARENTCODE not like", value, "parentcode");
			return (Criteria) this;
		}

		public Criteria andParentcodeIn(List<String> values) {
			addCriterion("PARENTCODE in", values, "parentcode");
			return (Criteria) this;
		}

		public Criteria andParentcodeNotIn(List<String> values) {
			addCriterion("PARENTCODE not in", values, "parentcode");
			return (Criteria) this;
		}

		public Criteria andParentcodeBetween(String value1, String value2) {
			addCriterion("PARENTCODE between", value1, value2, "parentcode");
			return (Criteria) this;
		}

		public Criteria andParentcodeNotBetween(String value1, String value2) {
			addCriterion("PARENTCODE not between", value1, value2, "parentcode");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table RESTAURANT.PERMISSION
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table permission
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 26 10:37:30 CAT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}