package dao.mybatis.model;

import java.util.Date;

public class Permission {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.PERMISSION.PERMISSION_DM
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String permissionDm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.PERMISSION.PERMISSION_MC
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String permissionMc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.PERMISSION.URL
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.PERMISSION.CREATE_DATE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.PERMISSION.CREATE_USER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.PERMISSION.DESCRIBES
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String describes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.PERMISSION.BEIZHU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String beizhu;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.PERMISSION.ALERT_DATE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private Date alertDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.PERMISSION.ALERT_USER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String alertUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.PERMISSION.ISUSE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String isuse;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.PERMISSION.PARENTCODE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String parentcode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.PERMISSION.PERMISSION_DM
	 * @return  the value of RESTAURANT.PERMISSION.PERMISSION_DM
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getPermissionDm() {
		return permissionDm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.PERMISSION.PERMISSION_DM
	 * @param permissionDm  the value for RESTAURANT.PERMISSION.PERMISSION_DM
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setPermissionDm(String permissionDm) {
		this.permissionDm = permissionDm == null ? null : permissionDm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.PERMISSION.PERMISSION_MC
	 * @return  the value of RESTAURANT.PERMISSION.PERMISSION_MC
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getPermissionMc() {
		return permissionMc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.PERMISSION.PERMISSION_MC
	 * @param permissionMc  the value for RESTAURANT.PERMISSION.PERMISSION_MC
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setPermissionMc(String permissionMc) {
		this.permissionMc = permissionMc == null ? null : permissionMc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.PERMISSION.URL
	 * @return  the value of RESTAURANT.PERMISSION.URL
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.PERMISSION.URL
	 * @param url  the value for RESTAURANT.PERMISSION.URL
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.PERMISSION.CREATE_DATE
	 * @return  the value of RESTAURANT.PERMISSION.CREATE_DATE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.PERMISSION.CREATE_DATE
	 * @param createDate  the value for RESTAURANT.PERMISSION.CREATE_DATE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.PERMISSION.CREATE_USER
	 * @return  the value of RESTAURANT.PERMISSION.CREATE_USER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.PERMISSION.CREATE_USER
	 * @param createUser  the value for RESTAURANT.PERMISSION.CREATE_USER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser == null ? null : createUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.PERMISSION.DESCRIBES
	 * @return  the value of RESTAURANT.PERMISSION.DESCRIBES
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getDescribes() {
		return describes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.PERMISSION.DESCRIBES
	 * @param describes  the value for RESTAURANT.PERMISSION.DESCRIBES
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setDescribes(String describes) {
		this.describes = describes == null ? null : describes.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.PERMISSION.BEIZHU
	 * @return  the value of RESTAURANT.PERMISSION.BEIZHU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getBeizhu() {
		return beizhu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.PERMISSION.BEIZHU
	 * @param beizhu  the value for RESTAURANT.PERMISSION.BEIZHU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setBeizhu(String beizhu) {
		this.beizhu = beizhu == null ? null : beizhu.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.PERMISSION.ALERT_DATE
	 * @return  the value of RESTAURANT.PERMISSION.ALERT_DATE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public Date getAlertDate() {
		return alertDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.PERMISSION.ALERT_DATE
	 * @param alertDate  the value for RESTAURANT.PERMISSION.ALERT_DATE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setAlertDate(Date alertDate) {
		this.alertDate = alertDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.PERMISSION.ALERT_USER
	 * @return  the value of RESTAURANT.PERMISSION.ALERT_USER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getAlertUser() {
		return alertUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.PERMISSION.ALERT_USER
	 * @param alertUser  the value for RESTAURANT.PERMISSION.ALERT_USER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setAlertUser(String alertUser) {
		this.alertUser = alertUser == null ? null : alertUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.PERMISSION.ISUSE
	 * @return  the value of RESTAURANT.PERMISSION.ISUSE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getIsuse() {
		return isuse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.PERMISSION.ISUSE
	 * @param isuse  the value for RESTAURANT.PERMISSION.ISUSE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setIsuse(String isuse) {
		this.isuse = isuse == null ? null : isuse.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.PERMISSION.PARENTCODE
	 * @return  the value of RESTAURANT.PERMISSION.PARENTCODE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getParentcode() {
		return parentcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.PERMISSION.PARENTCODE
	 * @param parentcode  the value for RESTAURANT.PERMISSION.PARENTCODE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setParentcode(String parentcode) {
		this.parentcode = parentcode == null ? null : parentcode.trim();
	}
}