package dao.mybatis.model;

import java.util.Date;

public class Product {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.PRODUCT.PRODUCTID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String productid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.PRODUCT.MC
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String mc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.PRODUCT.PRICE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.PRODUCT.PHOTO
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String photo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.PRODUCT.CREATE_DATE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.PRODUCT.CREATE_USER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.PRODUCT.ALTER_DATE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private Date alterDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.PRODUCT.ALTER_USER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String alterUser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.PRODUCT.PRODUCTID
	 * @return  the value of RESTAURANT.PRODUCT.PRODUCTID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getProductid() {
		return productid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.PRODUCT.PRODUCTID
	 * @param productid  the value for RESTAURANT.PRODUCT.PRODUCTID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setProductid(String productid) {
		this.productid = productid == null ? null : productid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.PRODUCT.MC
	 * @return  the value of RESTAURANT.PRODUCT.MC
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getMc() {
		return mc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.PRODUCT.MC
	 * @param mc  the value for RESTAURANT.PRODUCT.MC
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setMc(String mc) {
		this.mc = mc == null ? null : mc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.PRODUCT.PRICE
	 * @return  the value of RESTAURANT.PRODUCT.PRICE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.PRODUCT.PRICE
	 * @param price  the value for RESTAURANT.PRODUCT.PRICE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setPrice(String price) {
		this.price = price == null ? null : price.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.PRODUCT.PHOTO
	 * @return  the value of RESTAURANT.PRODUCT.PHOTO
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getPhoto() {
		return photo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.PRODUCT.PHOTO
	 * @param photo  the value for RESTAURANT.PRODUCT.PHOTO
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setPhoto(String photo) {
		this.photo = photo == null ? null : photo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.PRODUCT.CREATE_DATE
	 * @return  the value of RESTAURANT.PRODUCT.CREATE_DATE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.PRODUCT.CREATE_DATE
	 * @param createDate  the value for RESTAURANT.PRODUCT.CREATE_DATE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.PRODUCT.CREATE_USER
	 * @return  the value of RESTAURANT.PRODUCT.CREATE_USER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.PRODUCT.CREATE_USER
	 * @param createUser  the value for RESTAURANT.PRODUCT.CREATE_USER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser == null ? null : createUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.PRODUCT.ALTER_DATE
	 * @return  the value of RESTAURANT.PRODUCT.ALTER_DATE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public Date getAlterDate() {
		return alterDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.PRODUCT.ALTER_DATE
	 * @param alterDate  the value for RESTAURANT.PRODUCT.ALTER_DATE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setAlterDate(Date alterDate) {
		this.alterDate = alterDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.PRODUCT.ALTER_USER
	 * @return  the value of RESTAURANT.PRODUCT.ALTER_USER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getAlterUser() {
		return alterUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.PRODUCT.ALTER_USER
	 * @param alterUser  the value for RESTAURANT.PRODUCT.ALTER_USER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setAlterUser(String alterUser) {
		this.alterUser = alterUser == null ? null : alterUser.trim();
	}
}