package dao.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ProductExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RESTAURANT.PRODUCT
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RESTAURANT.PRODUCT
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RESTAURANT.PRODUCT
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PRODUCT
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public ProductExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PRODUCT
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PRODUCT
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PRODUCT
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PRODUCT
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PRODUCT
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PRODUCT
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PRODUCT
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PRODUCT
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PRODUCT
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.PRODUCT
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table RESTAURANT.PRODUCT
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andProductidIsNull() {
			addCriterion("PRODUCTID is null");
			return (Criteria) this;
		}

		public Criteria andProductidIsNotNull() {
			addCriterion("PRODUCTID is not null");
			return (Criteria) this;
		}

		public Criteria andProductidEqualTo(String value) {
			addCriterion("PRODUCTID =", value, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidNotEqualTo(String value) {
			addCriterion("PRODUCTID <>", value, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidGreaterThan(String value) {
			addCriterion("PRODUCTID >", value, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidGreaterThanOrEqualTo(String value) {
			addCriterion("PRODUCTID >=", value, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidLessThan(String value) {
			addCriterion("PRODUCTID <", value, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidLessThanOrEqualTo(String value) {
			addCriterion("PRODUCTID <=", value, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidLike(String value) {
			addCriterion("PRODUCTID like", value, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidNotLike(String value) {
			addCriterion("PRODUCTID not like", value, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidIn(List<String> values) {
			addCriterion("PRODUCTID in", values, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidNotIn(List<String> values) {
			addCriterion("PRODUCTID not in", values, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidBetween(String value1, String value2) {
			addCriterion("PRODUCTID between", value1, value2, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidNotBetween(String value1, String value2) {
			addCriterion("PRODUCTID not between", value1, value2, "productid");
			return (Criteria) this;
		}

		public Criteria andMcIsNull() {
			addCriterion("MC is null");
			return (Criteria) this;
		}

		public Criteria andMcIsNotNull() {
			addCriterion("MC is not null");
			return (Criteria) this;
		}

		public Criteria andMcEqualTo(String value) {
			addCriterion("MC =", value, "mc");
			return (Criteria) this;
		}

		public Criteria andMcNotEqualTo(String value) {
			addCriterion("MC <>", value, "mc");
			return (Criteria) this;
		}

		public Criteria andMcGreaterThan(String value) {
			addCriterion("MC >", value, "mc");
			return (Criteria) this;
		}

		public Criteria andMcGreaterThanOrEqualTo(String value) {
			addCriterion("MC >=", value, "mc");
			return (Criteria) this;
		}

		public Criteria andMcLessThan(String value) {
			addCriterion("MC <", value, "mc");
			return (Criteria) this;
		}

		public Criteria andMcLessThanOrEqualTo(String value) {
			addCriterion("MC <=", value, "mc");
			return (Criteria) this;
		}

		public Criteria andMcLike(String value) {
			addCriterion("MC like", value, "mc");
			return (Criteria) this;
		}

		public Criteria andMcNotLike(String value) {
			addCriterion("MC not like", value, "mc");
			return (Criteria) this;
		}

		public Criteria andMcIn(List<String> values) {
			addCriterion("MC in", values, "mc");
			return (Criteria) this;
		}

		public Criteria andMcNotIn(List<String> values) {
			addCriterion("MC not in", values, "mc");
			return (Criteria) this;
		}

		public Criteria andMcBetween(String value1, String value2) {
			addCriterion("MC between", value1, value2, "mc");
			return (Criteria) this;
		}

		public Criteria andMcNotBetween(String value1, String value2) {
			addCriterion("MC not between", value1, value2, "mc");
			return (Criteria) this;
		}

		public Criteria andPriceIsNull() {
			addCriterion("PRICE is null");
			return (Criteria) this;
		}

		public Criteria andPriceIsNotNull() {
			addCriterion("PRICE is not null");
			return (Criteria) this;
		}

		public Criteria andPriceEqualTo(String value) {
			addCriterion("PRICE =", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotEqualTo(String value) {
			addCriterion("PRICE <>", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThan(String value) {
			addCriterion("PRICE >", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThanOrEqualTo(String value) {
			addCriterion("PRICE >=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThan(String value) {
			addCriterion("PRICE <", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThanOrEqualTo(String value) {
			addCriterion("PRICE <=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLike(String value) {
			addCriterion("PRICE like", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotLike(String value) {
			addCriterion("PRICE not like", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceIn(List<String> values) {
			addCriterion("PRICE in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotIn(List<String> values) {
			addCriterion("PRICE not in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceBetween(String value1, String value2) {
			addCriterion("PRICE between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotBetween(String value1, String value2) {
			addCriterion("PRICE not between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPhotoIsNull() {
			addCriterion("PHOTO is null");
			return (Criteria) this;
		}

		public Criteria andPhotoIsNotNull() {
			addCriterion("PHOTO is not null");
			return (Criteria) this;
		}

		public Criteria andPhotoEqualTo(String value) {
			addCriterion("PHOTO =", value, "photo");
			return (Criteria) this;
		}

		public Criteria andPhotoNotEqualTo(String value) {
			addCriterion("PHOTO <>", value, "photo");
			return (Criteria) this;
		}

		public Criteria andPhotoGreaterThan(String value) {
			addCriterion("PHOTO >", value, "photo");
			return (Criteria) this;
		}

		public Criteria andPhotoGreaterThanOrEqualTo(String value) {
			addCriterion("PHOTO >=", value, "photo");
			return (Criteria) this;
		}

		public Criteria andPhotoLessThan(String value) {
			addCriterion("PHOTO <", value, "photo");
			return (Criteria) this;
		}

		public Criteria andPhotoLessThanOrEqualTo(String value) {
			addCriterion("PHOTO <=", value, "photo");
			return (Criteria) this;
		}

		public Criteria andPhotoLike(String value) {
			addCriterion("PHOTO like", value, "photo");
			return (Criteria) this;
		}

		public Criteria andPhotoNotLike(String value) {
			addCriterion("PHOTO not like", value, "photo");
			return (Criteria) this;
		}

		public Criteria andPhotoIn(List<String> values) {
			addCriterion("PHOTO in", values, "photo");
			return (Criteria) this;
		}

		public Criteria andPhotoNotIn(List<String> values) {
			addCriterion("PHOTO not in", values, "photo");
			return (Criteria) this;
		}

		public Criteria andPhotoBetween(String value1, String value2) {
			addCriterion("PHOTO between", value1, value2, "photo");
			return (Criteria) this;
		}

		public Criteria andPhotoNotBetween(String value1, String value2) {
			addCriterion("PHOTO not between", value1, value2, "photo");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("CREATE_DATE is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("CREATE_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_DATE =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_DATE <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterionForJDBCDate("CREATE_DATE >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_DATE >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterionForJDBCDate("CREATE_DATE <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_DATE <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterionForJDBCDate("CREATE_DATE in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("CREATE_DATE not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATE_DATE between", value1, value2,
					"createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATE_DATE not between", value1, value2,
					"createDate");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNull() {
			addCriterion("CREATE_USER is null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNotNull() {
			addCriterion("CREATE_USER is not null");
			return (Criteria) this;
		}

		public Criteria andCreateUserEqualTo(String value) {
			addCriterion("CREATE_USER =", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotEqualTo(String value) {
			addCriterion("CREATE_USER <>", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThan(String value) {
			addCriterion("CREATE_USER >", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
			addCriterion("CREATE_USER >=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThan(String value) {
			addCriterion("CREATE_USER <", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThanOrEqualTo(String value) {
			addCriterion("CREATE_USER <=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLike(String value) {
			addCriterion("CREATE_USER like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotLike(String value) {
			addCriterion("CREATE_USER not like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserIn(List<String> values) {
			addCriterion("CREATE_USER in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotIn(List<String> values) {
			addCriterion("CREATE_USER not in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserBetween(String value1, String value2) {
			addCriterion("CREATE_USER between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotBetween(String value1, String value2) {
			addCriterion("CREATE_USER not between", value1, value2,
					"createUser");
			return (Criteria) this;
		}

		public Criteria andAlterDateIsNull() {
			addCriterion("ALTER_DATE is null");
			return (Criteria) this;
		}

		public Criteria andAlterDateIsNotNull() {
			addCriterion("ALTER_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andAlterDateEqualTo(Date value) {
			addCriterionForJDBCDate("ALTER_DATE =", value, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("ALTER_DATE <>", value, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateGreaterThan(Date value) {
			addCriterionForJDBCDate("ALTER_DATE >", value, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ALTER_DATE >=", value, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateLessThan(Date value) {
			addCriterionForJDBCDate("ALTER_DATE <", value, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ALTER_DATE <=", value, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateIn(List<Date> values) {
			addCriterionForJDBCDate("ALTER_DATE in", values, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("ALTER_DATE not in", values, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ALTER_DATE between", value1, value2,
					"alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ALTER_DATE not between", value1, value2,
					"alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterUserIsNull() {
			addCriterion("ALTER_USER is null");
			return (Criteria) this;
		}

		public Criteria andAlterUserIsNotNull() {
			addCriterion("ALTER_USER is not null");
			return (Criteria) this;
		}

		public Criteria andAlterUserEqualTo(String value) {
			addCriterion("ALTER_USER =", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserNotEqualTo(String value) {
			addCriterion("ALTER_USER <>", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserGreaterThan(String value) {
			addCriterion("ALTER_USER >", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserGreaterThanOrEqualTo(String value) {
			addCriterion("ALTER_USER >=", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserLessThan(String value) {
			addCriterion("ALTER_USER <", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserLessThanOrEqualTo(String value) {
			addCriterion("ALTER_USER <=", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserLike(String value) {
			addCriterion("ALTER_USER like", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserNotLike(String value) {
			addCriterion("ALTER_USER not like", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserIn(List<String> values) {
			addCriterion("ALTER_USER in", values, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserNotIn(List<String> values) {
			addCriterion("ALTER_USER not in", values, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserBetween(String value1, String value2) {
			addCriterion("ALTER_USER between", value1, value2, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserNotBetween(String value1, String value2) {
			addCriterion("ALTER_USER not between", value1, value2, "alterUser");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table RESTAURANT.PRODUCT
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 26 10:37:30 CAT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}