package dao.mybatis.model;

import java.util.Date;

public class Role {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.ROLE.ROLE_DM
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String roleDm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.ROLE.ROLE_MC
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String roleMc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.ROLE.ISUSE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String isuse;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.ROLE.CREATETIME
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.ROLE.CREATEUSER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String createuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.ROLE.ALERTTIME
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private Date alerttime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.ROLE.ALERTUSER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String alertuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.ROLE.BEIZHU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String beizhu;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.ROLE.ROLE_DM
	 * @return  the value of RESTAURANT.ROLE.ROLE_DM
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getRoleDm() {
		return roleDm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.ROLE.ROLE_DM
	 * @param roleDm  the value for RESTAURANT.ROLE.ROLE_DM
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setRoleDm(String roleDm) {
		this.roleDm = roleDm == null ? null : roleDm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.ROLE.ROLE_MC
	 * @return  the value of RESTAURANT.ROLE.ROLE_MC
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getRoleMc() {
		return roleMc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.ROLE.ROLE_MC
	 * @param roleMc  the value for RESTAURANT.ROLE.ROLE_MC
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setRoleMc(String roleMc) {
		this.roleMc = roleMc == null ? null : roleMc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.ROLE.ISUSE
	 * @return  the value of RESTAURANT.ROLE.ISUSE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getIsuse() {
		return isuse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.ROLE.ISUSE
	 * @param isuse  the value for RESTAURANT.ROLE.ISUSE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setIsuse(String isuse) {
		this.isuse = isuse == null ? null : isuse.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.ROLE.CREATETIME
	 * @return  the value of RESTAURANT.ROLE.CREATETIME
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.ROLE.CREATETIME
	 * @param createtime  the value for RESTAURANT.ROLE.CREATETIME
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.ROLE.CREATEUSER
	 * @return  the value of RESTAURANT.ROLE.CREATEUSER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getCreateuser() {
		return createuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.ROLE.CREATEUSER
	 * @param createuser  the value for RESTAURANT.ROLE.CREATEUSER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setCreateuser(String createuser) {
		this.createuser = createuser == null ? null : createuser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.ROLE.ALERTTIME
	 * @return  the value of RESTAURANT.ROLE.ALERTTIME
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public Date getAlerttime() {
		return alerttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.ROLE.ALERTTIME
	 * @param alerttime  the value for RESTAURANT.ROLE.ALERTTIME
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setAlerttime(Date alerttime) {
		this.alerttime = alerttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.ROLE.ALERTUSER
	 * @return  the value of RESTAURANT.ROLE.ALERTUSER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getAlertuser() {
		return alertuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.ROLE.ALERTUSER
	 * @param alertuser  the value for RESTAURANT.ROLE.ALERTUSER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setAlertuser(String alertuser) {
		this.alertuser = alertuser == null ? null : alertuser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.ROLE.BEIZHU
	 * @return  the value of RESTAURANT.ROLE.BEIZHU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getBeizhu() {
		return beizhu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.ROLE.BEIZHU
	 * @param beizhu  the value for RESTAURANT.ROLE.BEIZHU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setBeizhu(String beizhu) {
		this.beizhu = beizhu == null ? null : beizhu.trim();
	}
}