package dao.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class RoleExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RESTAURANT.ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RESTAURANT.ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RESTAURANT.ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public RoleExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table RESTAURANT.ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andRoleDmIsNull() {
			addCriterion("ROLE_DM is null");
			return (Criteria) this;
		}

		public Criteria andRoleDmIsNotNull() {
			addCriterion("ROLE_DM is not null");
			return (Criteria) this;
		}

		public Criteria andRoleDmEqualTo(String value) {
			addCriterion("ROLE_DM =", value, "roleDm");
			return (Criteria) this;
		}

		public Criteria andRoleDmNotEqualTo(String value) {
			addCriterion("ROLE_DM <>", value, "roleDm");
			return (Criteria) this;
		}

		public Criteria andRoleDmGreaterThan(String value) {
			addCriterion("ROLE_DM >", value, "roleDm");
			return (Criteria) this;
		}

		public Criteria andRoleDmGreaterThanOrEqualTo(String value) {
			addCriterion("ROLE_DM >=", value, "roleDm");
			return (Criteria) this;
		}

		public Criteria andRoleDmLessThan(String value) {
			addCriterion("ROLE_DM <", value, "roleDm");
			return (Criteria) this;
		}

		public Criteria andRoleDmLessThanOrEqualTo(String value) {
			addCriterion("ROLE_DM <=", value, "roleDm");
			return (Criteria) this;
		}

		public Criteria andRoleDmLike(String value) {
			addCriterion("ROLE_DM like", value, "roleDm");
			return (Criteria) this;
		}

		public Criteria andRoleDmNotLike(String value) {
			addCriterion("ROLE_DM not like", value, "roleDm");
			return (Criteria) this;
		}

		public Criteria andRoleDmIn(List<String> values) {
			addCriterion("ROLE_DM in", values, "roleDm");
			return (Criteria) this;
		}

		public Criteria andRoleDmNotIn(List<String> values) {
			addCriterion("ROLE_DM not in", values, "roleDm");
			return (Criteria) this;
		}

		public Criteria andRoleDmBetween(String value1, String value2) {
			addCriterion("ROLE_DM between", value1, value2, "roleDm");
			return (Criteria) this;
		}

		public Criteria andRoleDmNotBetween(String value1, String value2) {
			addCriterion("ROLE_DM not between", value1, value2, "roleDm");
			return (Criteria) this;
		}

		public Criteria andRoleMcIsNull() {
			addCriterion("ROLE_MC is null");
			return (Criteria) this;
		}

		public Criteria andRoleMcIsNotNull() {
			addCriterion("ROLE_MC is not null");
			return (Criteria) this;
		}

		public Criteria andRoleMcEqualTo(String value) {
			addCriterion("ROLE_MC =", value, "roleMc");
			return (Criteria) this;
		}

		public Criteria andRoleMcNotEqualTo(String value) {
			addCriterion("ROLE_MC <>", value, "roleMc");
			return (Criteria) this;
		}

		public Criteria andRoleMcGreaterThan(String value) {
			addCriterion("ROLE_MC >", value, "roleMc");
			return (Criteria) this;
		}

		public Criteria andRoleMcGreaterThanOrEqualTo(String value) {
			addCriterion("ROLE_MC >=", value, "roleMc");
			return (Criteria) this;
		}

		public Criteria andRoleMcLessThan(String value) {
			addCriterion("ROLE_MC <", value, "roleMc");
			return (Criteria) this;
		}

		public Criteria andRoleMcLessThanOrEqualTo(String value) {
			addCriterion("ROLE_MC <=", value, "roleMc");
			return (Criteria) this;
		}

		public Criteria andRoleMcLike(String value) {
			addCriterion("ROLE_MC like", value, "roleMc");
			return (Criteria) this;
		}

		public Criteria andRoleMcNotLike(String value) {
			addCriterion("ROLE_MC not like", value, "roleMc");
			return (Criteria) this;
		}

		public Criteria andRoleMcIn(List<String> values) {
			addCriterion("ROLE_MC in", values, "roleMc");
			return (Criteria) this;
		}

		public Criteria andRoleMcNotIn(List<String> values) {
			addCriterion("ROLE_MC not in", values, "roleMc");
			return (Criteria) this;
		}

		public Criteria andRoleMcBetween(String value1, String value2) {
			addCriterion("ROLE_MC between", value1, value2, "roleMc");
			return (Criteria) this;
		}

		public Criteria andRoleMcNotBetween(String value1, String value2) {
			addCriterion("ROLE_MC not between", value1, value2, "roleMc");
			return (Criteria) this;
		}

		public Criteria andIsuseIsNull() {
			addCriterion("ISUSE is null");
			return (Criteria) this;
		}

		public Criteria andIsuseIsNotNull() {
			addCriterion("ISUSE is not null");
			return (Criteria) this;
		}

		public Criteria andIsuseEqualTo(String value) {
			addCriterion("ISUSE =", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseNotEqualTo(String value) {
			addCriterion("ISUSE <>", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseGreaterThan(String value) {
			addCriterion("ISUSE >", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseGreaterThanOrEqualTo(String value) {
			addCriterion("ISUSE >=", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseLessThan(String value) {
			addCriterion("ISUSE <", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseLessThanOrEqualTo(String value) {
			addCriterion("ISUSE <=", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseLike(String value) {
			addCriterion("ISUSE like", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseNotLike(String value) {
			addCriterion("ISUSE not like", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseIn(List<String> values) {
			addCriterion("ISUSE in", values, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseNotIn(List<String> values) {
			addCriterion("ISUSE not in", values, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseBetween(String value1, String value2) {
			addCriterion("ISUSE between", value1, value2, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseNotBetween(String value1, String value2) {
			addCriterion("ISUSE not between", value1, value2, "isuse");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNull() {
			addCriterion("CREATETIME is null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNotNull() {
			addCriterion("CREATETIME is not null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeEqualTo(Date value) {
			addCriterionForJDBCDate("CREATETIME =", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("CREATETIME <>", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThan(Date value) {
			addCriterionForJDBCDate("CREATETIME >", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATETIME >=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThan(Date value) {
			addCriterionForJDBCDate("CREATETIME <", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATETIME <=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIn(List<Date> values) {
			addCriterionForJDBCDate("CREATETIME in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("CREATETIME not in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATETIME between", value1, value2,
					"createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATETIME not between", value1, value2,
					"createtime");
			return (Criteria) this;
		}

		public Criteria andCreateuserIsNull() {
			addCriterion("CREATEUSER is null");
			return (Criteria) this;
		}

		public Criteria andCreateuserIsNotNull() {
			addCriterion("CREATEUSER is not null");
			return (Criteria) this;
		}

		public Criteria andCreateuserEqualTo(String value) {
			addCriterion("CREATEUSER =", value, "createuser");
			return (Criteria) this;
		}

		public Criteria andCreateuserNotEqualTo(String value) {
			addCriterion("CREATEUSER <>", value, "createuser");
			return (Criteria) this;
		}

		public Criteria andCreateuserGreaterThan(String value) {
			addCriterion("CREATEUSER >", value, "createuser");
			return (Criteria) this;
		}

		public Criteria andCreateuserGreaterThanOrEqualTo(String value) {
			addCriterion("CREATEUSER >=", value, "createuser");
			return (Criteria) this;
		}

		public Criteria andCreateuserLessThan(String value) {
			addCriterion("CREATEUSER <", value, "createuser");
			return (Criteria) this;
		}

		public Criteria andCreateuserLessThanOrEqualTo(String value) {
			addCriterion("CREATEUSER <=", value, "createuser");
			return (Criteria) this;
		}

		public Criteria andCreateuserLike(String value) {
			addCriterion("CREATEUSER like", value, "createuser");
			return (Criteria) this;
		}

		public Criteria andCreateuserNotLike(String value) {
			addCriterion("CREATEUSER not like", value, "createuser");
			return (Criteria) this;
		}

		public Criteria andCreateuserIn(List<String> values) {
			addCriterion("CREATEUSER in", values, "createuser");
			return (Criteria) this;
		}

		public Criteria andCreateuserNotIn(List<String> values) {
			addCriterion("CREATEUSER not in", values, "createuser");
			return (Criteria) this;
		}

		public Criteria andCreateuserBetween(String value1, String value2) {
			addCriterion("CREATEUSER between", value1, value2, "createuser");
			return (Criteria) this;
		}

		public Criteria andCreateuserNotBetween(String value1, String value2) {
			addCriterion("CREATEUSER not between", value1, value2, "createuser");
			return (Criteria) this;
		}

		public Criteria andAlerttimeIsNull() {
			addCriterion("ALERTTIME is null");
			return (Criteria) this;
		}

		public Criteria andAlerttimeIsNotNull() {
			addCriterion("ALERTTIME is not null");
			return (Criteria) this;
		}

		public Criteria andAlerttimeEqualTo(Date value) {
			addCriterionForJDBCDate("ALERTTIME =", value, "alerttime");
			return (Criteria) this;
		}

		public Criteria andAlerttimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("ALERTTIME <>", value, "alerttime");
			return (Criteria) this;
		}

		public Criteria andAlerttimeGreaterThan(Date value) {
			addCriterionForJDBCDate("ALERTTIME >", value, "alerttime");
			return (Criteria) this;
		}

		public Criteria andAlerttimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ALERTTIME >=", value, "alerttime");
			return (Criteria) this;
		}

		public Criteria andAlerttimeLessThan(Date value) {
			addCriterionForJDBCDate("ALERTTIME <", value, "alerttime");
			return (Criteria) this;
		}

		public Criteria andAlerttimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ALERTTIME <=", value, "alerttime");
			return (Criteria) this;
		}

		public Criteria andAlerttimeIn(List<Date> values) {
			addCriterionForJDBCDate("ALERTTIME in", values, "alerttime");
			return (Criteria) this;
		}

		public Criteria andAlerttimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("ALERTTIME not in", values, "alerttime");
			return (Criteria) this;
		}

		public Criteria andAlerttimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ALERTTIME between", value1, value2,
					"alerttime");
			return (Criteria) this;
		}

		public Criteria andAlerttimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ALERTTIME not between", value1, value2,
					"alerttime");
			return (Criteria) this;
		}

		public Criteria andAlertuserIsNull() {
			addCriterion("ALERTUSER is null");
			return (Criteria) this;
		}

		public Criteria andAlertuserIsNotNull() {
			addCriterion("ALERTUSER is not null");
			return (Criteria) this;
		}

		public Criteria andAlertuserEqualTo(String value) {
			addCriterion("ALERTUSER =", value, "alertuser");
			return (Criteria) this;
		}

		public Criteria andAlertuserNotEqualTo(String value) {
			addCriterion("ALERTUSER <>", value, "alertuser");
			return (Criteria) this;
		}

		public Criteria andAlertuserGreaterThan(String value) {
			addCriterion("ALERTUSER >", value, "alertuser");
			return (Criteria) this;
		}

		public Criteria andAlertuserGreaterThanOrEqualTo(String value) {
			addCriterion("ALERTUSER >=", value, "alertuser");
			return (Criteria) this;
		}

		public Criteria andAlertuserLessThan(String value) {
			addCriterion("ALERTUSER <", value, "alertuser");
			return (Criteria) this;
		}

		public Criteria andAlertuserLessThanOrEqualTo(String value) {
			addCriterion("ALERTUSER <=", value, "alertuser");
			return (Criteria) this;
		}

		public Criteria andAlertuserLike(String value) {
			addCriterion("ALERTUSER like", value, "alertuser");
			return (Criteria) this;
		}

		public Criteria andAlertuserNotLike(String value) {
			addCriterion("ALERTUSER not like", value, "alertuser");
			return (Criteria) this;
		}

		public Criteria andAlertuserIn(List<String> values) {
			addCriterion("ALERTUSER in", values, "alertuser");
			return (Criteria) this;
		}

		public Criteria andAlertuserNotIn(List<String> values) {
			addCriterion("ALERTUSER not in", values, "alertuser");
			return (Criteria) this;
		}

		public Criteria andAlertuserBetween(String value1, String value2) {
			addCriterion("ALERTUSER between", value1, value2, "alertuser");
			return (Criteria) this;
		}

		public Criteria andAlertuserNotBetween(String value1, String value2) {
			addCriterion("ALERTUSER not between", value1, value2, "alertuser");
			return (Criteria) this;
		}

		public Criteria andBeizhuIsNull() {
			addCriterion("BEIZHU is null");
			return (Criteria) this;
		}

		public Criteria andBeizhuIsNotNull() {
			addCriterion("BEIZHU is not null");
			return (Criteria) this;
		}

		public Criteria andBeizhuEqualTo(String value) {
			addCriterion("BEIZHU =", value, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuNotEqualTo(String value) {
			addCriterion("BEIZHU <>", value, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuGreaterThan(String value) {
			addCriterion("BEIZHU >", value, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuGreaterThanOrEqualTo(String value) {
			addCriterion("BEIZHU >=", value, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuLessThan(String value) {
			addCriterion("BEIZHU <", value, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuLessThanOrEqualTo(String value) {
			addCriterion("BEIZHU <=", value, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuLike(String value) {
			addCriterion("BEIZHU like", value, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuNotLike(String value) {
			addCriterion("BEIZHU not like", value, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuIn(List<String> values) {
			addCriterion("BEIZHU in", values, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuNotIn(List<String> values) {
			addCriterion("BEIZHU not in", values, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuBetween(String value1, String value2) {
			addCriterion("BEIZHU between", value1, value2, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuNotBetween(String value1, String value2) {
			addCriterion("BEIZHU not between", value1, value2, "beizhu");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table RESTAURANT.ROLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table role
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 26 10:37:30 CAT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}