package dao.mybatis.model;

import java.util.Date;

public class Stru {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.STRU.JG_DM
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String jgDm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.STRU.JG_MC
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String jgMc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.STRU.IS_USE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String isUse;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.STRU.PARENT_JGDM
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String parentJgdm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.STRU.CREATE_DATE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.STRU.CREATE_USER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.STRU.ALTER_DATE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private Date alterDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.STRU.ALTER_USER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String alterUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.STRU.BEIZHU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String beizhu;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.STRU.JG_DM
	 * @return  the value of RESTAURANT.STRU.JG_DM
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getJgDm() {
		return jgDm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.STRU.JG_DM
	 * @param jgDm  the value for RESTAURANT.STRU.JG_DM
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setJgDm(String jgDm) {
		this.jgDm = jgDm == null ? null : jgDm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.STRU.JG_MC
	 * @return  the value of RESTAURANT.STRU.JG_MC
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getJgMc() {
		return jgMc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.STRU.JG_MC
	 * @param jgMc  the value for RESTAURANT.STRU.JG_MC
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setJgMc(String jgMc) {
		this.jgMc = jgMc == null ? null : jgMc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.STRU.IS_USE
	 * @return  the value of RESTAURANT.STRU.IS_USE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getIsUse() {
		return isUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.STRU.IS_USE
	 * @param isUse  the value for RESTAURANT.STRU.IS_USE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setIsUse(String isUse) {
		this.isUse = isUse == null ? null : isUse.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.STRU.PARENT_JGDM
	 * @return  the value of RESTAURANT.STRU.PARENT_JGDM
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getParentJgdm() {
		return parentJgdm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.STRU.PARENT_JGDM
	 * @param parentJgdm  the value for RESTAURANT.STRU.PARENT_JGDM
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setParentJgdm(String parentJgdm) {
		this.parentJgdm = parentJgdm == null ? null : parentJgdm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.STRU.CREATE_DATE
	 * @return  the value of RESTAURANT.STRU.CREATE_DATE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.STRU.CREATE_DATE
	 * @param createDate  the value for RESTAURANT.STRU.CREATE_DATE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.STRU.CREATE_USER
	 * @return  the value of RESTAURANT.STRU.CREATE_USER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.STRU.CREATE_USER
	 * @param createUser  the value for RESTAURANT.STRU.CREATE_USER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser == null ? null : createUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.STRU.ALTER_DATE
	 * @return  the value of RESTAURANT.STRU.ALTER_DATE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public Date getAlterDate() {
		return alterDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.STRU.ALTER_DATE
	 * @param alterDate  the value for RESTAURANT.STRU.ALTER_DATE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setAlterDate(Date alterDate) {
		this.alterDate = alterDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.STRU.ALTER_USER
	 * @return  the value of RESTAURANT.STRU.ALTER_USER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getAlterUser() {
		return alterUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.STRU.ALTER_USER
	 * @param alterUser  the value for RESTAURANT.STRU.ALTER_USER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setAlterUser(String alterUser) {
		this.alterUser = alterUser == null ? null : alterUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.STRU.BEIZHU
	 * @return  the value of RESTAURANT.STRU.BEIZHU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getBeizhu() {
		return beizhu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.STRU.BEIZHU
	 * @param beizhu  the value for RESTAURANT.STRU.BEIZHU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setBeizhu(String beizhu) {
		this.beizhu = beizhu == null ? null : beizhu.trim();
	}
}