package dao.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class StruExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RESTAURANT.STRU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RESTAURANT.STRU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RESTAURANT.STRU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.STRU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public StruExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.STRU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.STRU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.STRU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.STRU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.STRU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.STRU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.STRU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.STRU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.STRU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.STRU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table RESTAURANT.STRU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andJgDmIsNull() {
			addCriterion("JG_DM is null");
			return (Criteria) this;
		}

		public Criteria andJgDmIsNotNull() {
			addCriterion("JG_DM is not null");
			return (Criteria) this;
		}

		public Criteria andJgDmEqualTo(String value) {
			addCriterion("JG_DM =", value, "jgDm");
			return (Criteria) this;
		}

		public Criteria andJgDmNotEqualTo(String value) {
			addCriterion("JG_DM <>", value, "jgDm");
			return (Criteria) this;
		}

		public Criteria andJgDmGreaterThan(String value) {
			addCriterion("JG_DM >", value, "jgDm");
			return (Criteria) this;
		}

		public Criteria andJgDmGreaterThanOrEqualTo(String value) {
			addCriterion("JG_DM >=", value, "jgDm");
			return (Criteria) this;
		}

		public Criteria andJgDmLessThan(String value) {
			addCriterion("JG_DM <", value, "jgDm");
			return (Criteria) this;
		}

		public Criteria andJgDmLessThanOrEqualTo(String value) {
			addCriterion("JG_DM <=", value, "jgDm");
			return (Criteria) this;
		}

		public Criteria andJgDmLike(String value) {
			addCriterion("JG_DM like", value, "jgDm");
			return (Criteria) this;
		}

		public Criteria andJgDmNotLike(String value) {
			addCriterion("JG_DM not like", value, "jgDm");
			return (Criteria) this;
		}

		public Criteria andJgDmIn(List<String> values) {
			addCriterion("JG_DM in", values, "jgDm");
			return (Criteria) this;
		}

		public Criteria andJgDmNotIn(List<String> values) {
			addCriterion("JG_DM not in", values, "jgDm");
			return (Criteria) this;
		}

		public Criteria andJgDmBetween(String value1, String value2) {
			addCriterion("JG_DM between", value1, value2, "jgDm");
			return (Criteria) this;
		}

		public Criteria andJgDmNotBetween(String value1, String value2) {
			addCriterion("JG_DM not between", value1, value2, "jgDm");
			return (Criteria) this;
		}

		public Criteria andJgMcIsNull() {
			addCriterion("JG_MC is null");
			return (Criteria) this;
		}

		public Criteria andJgMcIsNotNull() {
			addCriterion("JG_MC is not null");
			return (Criteria) this;
		}

		public Criteria andJgMcEqualTo(String value) {
			addCriterion("JG_MC =", value, "jgMc");
			return (Criteria) this;
		}

		public Criteria andJgMcNotEqualTo(String value) {
			addCriterion("JG_MC <>", value, "jgMc");
			return (Criteria) this;
		}

		public Criteria andJgMcGreaterThan(String value) {
			addCriterion("JG_MC >", value, "jgMc");
			return (Criteria) this;
		}

		public Criteria andJgMcGreaterThanOrEqualTo(String value) {
			addCriterion("JG_MC >=", value, "jgMc");
			return (Criteria) this;
		}

		public Criteria andJgMcLessThan(String value) {
			addCriterion("JG_MC <", value, "jgMc");
			return (Criteria) this;
		}

		public Criteria andJgMcLessThanOrEqualTo(String value) {
			addCriterion("JG_MC <=", value, "jgMc");
			return (Criteria) this;
		}

		public Criteria andJgMcLike(String value) {
			addCriterion("JG_MC like", value, "jgMc");
			return (Criteria) this;
		}

		public Criteria andJgMcNotLike(String value) {
			addCriterion("JG_MC not like", value, "jgMc");
			return (Criteria) this;
		}

		public Criteria andJgMcIn(List<String> values) {
			addCriterion("JG_MC in", values, "jgMc");
			return (Criteria) this;
		}

		public Criteria andJgMcNotIn(List<String> values) {
			addCriterion("JG_MC not in", values, "jgMc");
			return (Criteria) this;
		}

		public Criteria andJgMcBetween(String value1, String value2) {
			addCriterion("JG_MC between", value1, value2, "jgMc");
			return (Criteria) this;
		}

		public Criteria andJgMcNotBetween(String value1, String value2) {
			addCriterion("JG_MC not between", value1, value2, "jgMc");
			return (Criteria) this;
		}

		public Criteria andIsUseIsNull() {
			addCriterion("IS_USE is null");
			return (Criteria) this;
		}

		public Criteria andIsUseIsNotNull() {
			addCriterion("IS_USE is not null");
			return (Criteria) this;
		}

		public Criteria andIsUseEqualTo(String value) {
			addCriterion("IS_USE =", value, "isUse");
			return (Criteria) this;
		}

		public Criteria andIsUseNotEqualTo(String value) {
			addCriterion("IS_USE <>", value, "isUse");
			return (Criteria) this;
		}

		public Criteria andIsUseGreaterThan(String value) {
			addCriterion("IS_USE >", value, "isUse");
			return (Criteria) this;
		}

		public Criteria andIsUseGreaterThanOrEqualTo(String value) {
			addCriterion("IS_USE >=", value, "isUse");
			return (Criteria) this;
		}

		public Criteria andIsUseLessThan(String value) {
			addCriterion("IS_USE <", value, "isUse");
			return (Criteria) this;
		}

		public Criteria andIsUseLessThanOrEqualTo(String value) {
			addCriterion("IS_USE <=", value, "isUse");
			return (Criteria) this;
		}

		public Criteria andIsUseLike(String value) {
			addCriterion("IS_USE like", value, "isUse");
			return (Criteria) this;
		}

		public Criteria andIsUseNotLike(String value) {
			addCriterion("IS_USE not like", value, "isUse");
			return (Criteria) this;
		}

		public Criteria andIsUseIn(List<String> values) {
			addCriterion("IS_USE in", values, "isUse");
			return (Criteria) this;
		}

		public Criteria andIsUseNotIn(List<String> values) {
			addCriterion("IS_USE not in", values, "isUse");
			return (Criteria) this;
		}

		public Criteria andIsUseBetween(String value1, String value2) {
			addCriterion("IS_USE between", value1, value2, "isUse");
			return (Criteria) this;
		}

		public Criteria andIsUseNotBetween(String value1, String value2) {
			addCriterion("IS_USE not between", value1, value2, "isUse");
			return (Criteria) this;
		}

		public Criteria andParentJgdmIsNull() {
			addCriterion("PARENT_JGDM is null");
			return (Criteria) this;
		}

		public Criteria andParentJgdmIsNotNull() {
			addCriterion("PARENT_JGDM is not null");
			return (Criteria) this;
		}

		public Criteria andParentJgdmEqualTo(String value) {
			addCriterion("PARENT_JGDM =", value, "parentJgdm");
			return (Criteria) this;
		}

		public Criteria andParentJgdmNotEqualTo(String value) {
			addCriterion("PARENT_JGDM <>", value, "parentJgdm");
			return (Criteria) this;
		}

		public Criteria andParentJgdmGreaterThan(String value) {
			addCriterion("PARENT_JGDM >", value, "parentJgdm");
			return (Criteria) this;
		}

		public Criteria andParentJgdmGreaterThanOrEqualTo(String value) {
			addCriterion("PARENT_JGDM >=", value, "parentJgdm");
			return (Criteria) this;
		}

		public Criteria andParentJgdmLessThan(String value) {
			addCriterion("PARENT_JGDM <", value, "parentJgdm");
			return (Criteria) this;
		}

		public Criteria andParentJgdmLessThanOrEqualTo(String value) {
			addCriterion("PARENT_JGDM <=", value, "parentJgdm");
			return (Criteria) this;
		}

		public Criteria andParentJgdmLike(String value) {
			addCriterion("PARENT_JGDM like", value, "parentJgdm");
			return (Criteria) this;
		}

		public Criteria andParentJgdmNotLike(String value) {
			addCriterion("PARENT_JGDM not like", value, "parentJgdm");
			return (Criteria) this;
		}

		public Criteria andParentJgdmIn(List<String> values) {
			addCriterion("PARENT_JGDM in", values, "parentJgdm");
			return (Criteria) this;
		}

		public Criteria andParentJgdmNotIn(List<String> values) {
			addCriterion("PARENT_JGDM not in", values, "parentJgdm");
			return (Criteria) this;
		}

		public Criteria andParentJgdmBetween(String value1, String value2) {
			addCriterion("PARENT_JGDM between", value1, value2, "parentJgdm");
			return (Criteria) this;
		}

		public Criteria andParentJgdmNotBetween(String value1, String value2) {
			addCriterion("PARENT_JGDM not between", value1, value2,
					"parentJgdm");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("CREATE_DATE is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("CREATE_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_DATE =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_DATE <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterionForJDBCDate("CREATE_DATE >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_DATE >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterionForJDBCDate("CREATE_DATE <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_DATE <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterionForJDBCDate("CREATE_DATE in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("CREATE_DATE not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATE_DATE between", value1, value2,
					"createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATE_DATE not between", value1, value2,
					"createDate");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNull() {
			addCriterion("CREATE_USER is null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNotNull() {
			addCriterion("CREATE_USER is not null");
			return (Criteria) this;
		}

		public Criteria andCreateUserEqualTo(String value) {
			addCriterion("CREATE_USER =", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotEqualTo(String value) {
			addCriterion("CREATE_USER <>", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThan(String value) {
			addCriterion("CREATE_USER >", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
			addCriterion("CREATE_USER >=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThan(String value) {
			addCriterion("CREATE_USER <", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThanOrEqualTo(String value) {
			addCriterion("CREATE_USER <=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLike(String value) {
			addCriterion("CREATE_USER like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotLike(String value) {
			addCriterion("CREATE_USER not like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserIn(List<String> values) {
			addCriterion("CREATE_USER in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotIn(List<String> values) {
			addCriterion("CREATE_USER not in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserBetween(String value1, String value2) {
			addCriterion("CREATE_USER between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotBetween(String value1, String value2) {
			addCriterion("CREATE_USER not between", value1, value2,
					"createUser");
			return (Criteria) this;
		}

		public Criteria andAlterDateIsNull() {
			addCriterion("ALTER_DATE is null");
			return (Criteria) this;
		}

		public Criteria andAlterDateIsNotNull() {
			addCriterion("ALTER_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andAlterDateEqualTo(Date value) {
			addCriterionForJDBCDate("ALTER_DATE =", value, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("ALTER_DATE <>", value, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateGreaterThan(Date value) {
			addCriterionForJDBCDate("ALTER_DATE >", value, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ALTER_DATE >=", value, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateLessThan(Date value) {
			addCriterionForJDBCDate("ALTER_DATE <", value, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ALTER_DATE <=", value, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateIn(List<Date> values) {
			addCriterionForJDBCDate("ALTER_DATE in", values, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("ALTER_DATE not in", values, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ALTER_DATE between", value1, value2,
					"alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ALTER_DATE not between", value1, value2,
					"alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterUserIsNull() {
			addCriterion("ALTER_USER is null");
			return (Criteria) this;
		}

		public Criteria andAlterUserIsNotNull() {
			addCriterion("ALTER_USER is not null");
			return (Criteria) this;
		}

		public Criteria andAlterUserEqualTo(String value) {
			addCriterion("ALTER_USER =", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserNotEqualTo(String value) {
			addCriterion("ALTER_USER <>", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserGreaterThan(String value) {
			addCriterion("ALTER_USER >", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserGreaterThanOrEqualTo(String value) {
			addCriterion("ALTER_USER >=", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserLessThan(String value) {
			addCriterion("ALTER_USER <", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserLessThanOrEqualTo(String value) {
			addCriterion("ALTER_USER <=", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserLike(String value) {
			addCriterion("ALTER_USER like", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserNotLike(String value) {
			addCriterion("ALTER_USER not like", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserIn(List<String> values) {
			addCriterion("ALTER_USER in", values, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserNotIn(List<String> values) {
			addCriterion("ALTER_USER not in", values, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserBetween(String value1, String value2) {
			addCriterion("ALTER_USER between", value1, value2, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserNotBetween(String value1, String value2) {
			addCriterion("ALTER_USER not between", value1, value2, "alterUser");
			return (Criteria) this;
		}

		public Criteria andBeizhuIsNull() {
			addCriterion("BEIZHU is null");
			return (Criteria) this;
		}

		public Criteria andBeizhuIsNotNull() {
			addCriterion("BEIZHU is not null");
			return (Criteria) this;
		}

		public Criteria andBeizhuEqualTo(String value) {
			addCriterion("BEIZHU =", value, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuNotEqualTo(String value) {
			addCriterion("BEIZHU <>", value, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuGreaterThan(String value) {
			addCriterion("BEIZHU >", value, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuGreaterThanOrEqualTo(String value) {
			addCriterion("BEIZHU >=", value, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuLessThan(String value) {
			addCriterion("BEIZHU <", value, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuLessThanOrEqualTo(String value) {
			addCriterion("BEIZHU <=", value, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuLike(String value) {
			addCriterion("BEIZHU like", value, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuNotLike(String value) {
			addCriterion("BEIZHU not like", value, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuIn(List<String> values) {
			addCriterion("BEIZHU in", values, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuNotIn(List<String> values) {
			addCriterion("BEIZHU not in", values, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuBetween(String value1, String value2) {
			addCriterion("BEIZHU between", value1, value2, "beizhu");
			return (Criteria) this;
		}

		public Criteria andBeizhuNotBetween(String value1, String value2) {
			addCriterion("BEIZHU not between", value1, value2, "beizhu");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table RESTAURANT.STRU
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stru
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 26 10:37:30 CAT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}