package dao.mybatis.model;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.USERS.ID
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.USERS.USERID
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	private String userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.USERS.USERNAME
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.USERS.PASSWORD
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.USERS.TELPHONE
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	private String telphone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.USERS.EMAIL
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.USERS.QQ
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	private String qq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.USERS.WEIXIN
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	private String weixin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.USERS.SEX
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.USERS.OCCUPATION
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	private String occupation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.USERS.AGE
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	private String age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.USERS.LOGO
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	private String logo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.USERS.STATE
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	private String state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.USERS.ISUSE
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	private String isuse;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.USERS.JGNM
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	private String jgnm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.USERS.TYPE
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.USERS.CREATE_DATE
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.USERS.CREATE_USER
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.USERS.ALTER_DATE
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	private Date alterDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.USERS.ALTER_USER
	 * @mbggenerated  Thu Nov 26 13:38:43 CAT 2015
	 */
	private String alterUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.USERS.DOMAIN
	 * @mbggenerated  Thu Nov 26 13:38:43 CAT 2015
	 */
	private String domain;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.USERS.HOMEPAGE
	 * @mbggenerated  Thu Nov 26 13:38:43 CAT 2015
	 */
	private String homepage;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.USERS.ID
	 * @return  the value of RESTAURANT.USERS.ID
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.USERS.ID
	 * @param id  the value for RESTAURANT.USERS.ID
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.USERS.USERID
	 * @return  the value of RESTAURANT.USERS.USERID
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.USERS.USERID
	 * @param userid  the value for RESTAURANT.USERS.USERID
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public void setUserid(String userid) {
		this.userid = userid == null ? null : userid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.USERS.USERNAME
	 * @return  the value of RESTAURANT.USERS.USERNAME
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.USERS.USERNAME
	 * @param username  the value for RESTAURANT.USERS.USERNAME
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.USERS.PASSWORD
	 * @return  the value of RESTAURANT.USERS.PASSWORD
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.USERS.PASSWORD
	 * @param password  the value for RESTAURANT.USERS.PASSWORD
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.USERS.TELPHONE
	 * @return  the value of RESTAURANT.USERS.TELPHONE
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public String getTelphone() {
		return telphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.USERS.TELPHONE
	 * @param telphone  the value for RESTAURANT.USERS.TELPHONE
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public void setTelphone(String telphone) {
		this.telphone = telphone == null ? null : telphone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.USERS.EMAIL
	 * @return  the value of RESTAURANT.USERS.EMAIL
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.USERS.EMAIL
	 * @param email  the value for RESTAURANT.USERS.EMAIL
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.USERS.QQ
	 * @return  the value of RESTAURANT.USERS.QQ
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public String getQq() {
		return qq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.USERS.QQ
	 * @param qq  the value for RESTAURANT.USERS.QQ
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public void setQq(String qq) {
		this.qq = qq == null ? null : qq.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.USERS.WEIXIN
	 * @return  the value of RESTAURANT.USERS.WEIXIN
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public String getWeixin() {
		return weixin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.USERS.WEIXIN
	 * @param weixin  the value for RESTAURANT.USERS.WEIXIN
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public void setWeixin(String weixin) {
		this.weixin = weixin == null ? null : weixin.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.USERS.SEX
	 * @return  the value of RESTAURANT.USERS.SEX
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.USERS.SEX
	 * @param sex  the value for RESTAURANT.USERS.SEX
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public void setSex(String sex) {
		this.sex = sex == null ? null : sex.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.USERS.OCCUPATION
	 * @return  the value of RESTAURANT.USERS.OCCUPATION
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public String getOccupation() {
		return occupation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.USERS.OCCUPATION
	 * @param occupation  the value for RESTAURANT.USERS.OCCUPATION
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public void setOccupation(String occupation) {
		this.occupation = occupation == null ? null : occupation.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.USERS.AGE
	 * @return  the value of RESTAURANT.USERS.AGE
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public String getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.USERS.AGE
	 * @param age  the value for RESTAURANT.USERS.AGE
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public void setAge(String age) {
		this.age = age == null ? null : age.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.USERS.LOGO
	 * @return  the value of RESTAURANT.USERS.LOGO
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public String getLogo() {
		return logo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.USERS.LOGO
	 * @param logo  the value for RESTAURANT.USERS.LOGO
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public void setLogo(String logo) {
		this.logo = logo == null ? null : logo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.USERS.STATE
	 * @return  the value of RESTAURANT.USERS.STATE
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.USERS.STATE
	 * @param state  the value for RESTAURANT.USERS.STATE
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public void setState(String state) {
		this.state = state == null ? null : state.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.USERS.ISUSE
	 * @return  the value of RESTAURANT.USERS.ISUSE
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public String getIsuse() {
		return isuse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.USERS.ISUSE
	 * @param isuse  the value for RESTAURANT.USERS.ISUSE
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public void setIsuse(String isuse) {
		this.isuse = isuse == null ? null : isuse.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.USERS.JGNM
	 * @return  the value of RESTAURANT.USERS.JGNM
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public String getJgnm() {
		return jgnm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.USERS.JGNM
	 * @param jgnm  the value for RESTAURANT.USERS.JGNM
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public void setJgnm(String jgnm) {
		this.jgnm = jgnm == null ? null : jgnm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.USERS.TYPE
	 * @return  the value of RESTAURANT.USERS.TYPE
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.USERS.TYPE
	 * @param type  the value for RESTAURANT.USERS.TYPE
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.USERS.CREATE_DATE
	 * @return  the value of RESTAURANT.USERS.CREATE_DATE
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.USERS.CREATE_DATE
	 * @param createDate  the value for RESTAURANT.USERS.CREATE_DATE
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.USERS.CREATE_USER
	 * @return  the value of RESTAURANT.USERS.CREATE_USER
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.USERS.CREATE_USER
	 * @param createUser  the value for RESTAURANT.USERS.CREATE_USER
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser == null ? null : createUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.USERS.ALTER_DATE
	 * @return  the value of RESTAURANT.USERS.ALTER_DATE
	 * @mbggenerated  Thu Nov 26 13:38:43 CAT 2015
	 */
	public Date getAlterDate() {
		return alterDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.USERS.ALTER_DATE
	 * @param alterDate  the value for RESTAURANT.USERS.ALTER_DATE
	 * @mbggenerated  Thu Nov 26 13:38:43 CAT 2015
	 */
	public void setAlterDate(Date alterDate) {
		this.alterDate = alterDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.USERS.ALTER_USER
	 * @return  the value of RESTAURANT.USERS.ALTER_USER
	 * @mbggenerated  Thu Nov 26 13:38:43 CAT 2015
	 */
	public String getAlterUser() {
		return alterUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.USERS.ALTER_USER
	 * @param alterUser  the value for RESTAURANT.USERS.ALTER_USER
	 * @mbggenerated  Thu Nov 26 13:38:43 CAT 2015
	 */
	public void setAlterUser(String alterUser) {
		this.alterUser = alterUser == null ? null : alterUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.USERS.DOMAIN
	 * @return  the value of RESTAURANT.USERS.DOMAIN
	 * @mbggenerated  Thu Nov 26 13:38:43 CAT 2015
	 */
	public String getDomain() {
		return domain;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.USERS.DOMAIN
	 * @param domain  the value for RESTAURANT.USERS.DOMAIN
	 * @mbggenerated  Thu Nov 26 13:38:43 CAT 2015
	 */
	public void setDomain(String domain) {
		this.domain = domain == null ? null : domain.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.USERS.HOMEPAGE
	 * @return  the value of RESTAURANT.USERS.HOMEPAGE
	 * @mbggenerated  Thu Nov 26 13:38:43 CAT 2015
	 */
	public String getHomepage() {
		return homepage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.USERS.HOMEPAGE
	 * @param homepage  the value for RESTAURANT.USERS.HOMEPAGE
	 * @mbggenerated  Thu Nov 26 13:38:43 CAT 2015
	 */
	public void setHomepage(String homepage) {
		this.homepage = homepage == null ? null : homepage.trim();
	}
}