package dao.mybatis.model;

import java.util.Date;

public class User_role {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.USER_ROLE.ID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.USER_ROLE.USERID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.USER_ROLE.ROLEID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String roleid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.USER_ROLE.DESCRIBLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String describle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.USER_ROLE.CREATEUSER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String createuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.USER_ROLE.CREATETIME
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private Date createtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.USER_ROLE.ID
	 * @return  the value of RESTAURANT.USER_ROLE.ID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.USER_ROLE.ID
	 * @param id  the value for RESTAURANT.USER_ROLE.ID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.USER_ROLE.USERID
	 * @return  the value of RESTAURANT.USER_ROLE.USERID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.USER_ROLE.USERID
	 * @param userid  the value for RESTAURANT.USER_ROLE.USERID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setUserid(String userid) {
		this.userid = userid == null ? null : userid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.USER_ROLE.ROLEID
	 * @return  the value of RESTAURANT.USER_ROLE.ROLEID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getRoleid() {
		return roleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.USER_ROLE.ROLEID
	 * @param roleid  the value for RESTAURANT.USER_ROLE.ROLEID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setRoleid(String roleid) {
		this.roleid = roleid == null ? null : roleid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.USER_ROLE.DESCRIBLE
	 * @return  the value of RESTAURANT.USER_ROLE.DESCRIBLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getDescrible() {
		return describle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.USER_ROLE.DESCRIBLE
	 * @param describle  the value for RESTAURANT.USER_ROLE.DESCRIBLE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setDescrible(String describle) {
		this.describle = describle == null ? null : describle.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.USER_ROLE.CREATEUSER
	 * @return  the value of RESTAURANT.USER_ROLE.CREATEUSER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getCreateuser() {
		return createuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.USER_ROLE.CREATEUSER
	 * @param createuser  the value for RESTAURANT.USER_ROLE.CREATEUSER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setCreateuser(String createuser) {
		this.createuser = createuser == null ? null : createuser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.USER_ROLE.CREATETIME
	 * @return  the value of RESTAURANT.USER_ROLE.CREATETIME
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.USER_ROLE.CREATETIME
	 * @param createtime  the value for RESTAURANT.USER_ROLE.CREATETIME
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}
}