package dao.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class UserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RESTAURANT.USERS
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RESTAURANT.USERS
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RESTAURANT.USERS
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USERS
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public UserExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USERS
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USERS
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USERS
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USERS
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USERS
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USERS
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USERS
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USERS
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USERS
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.USERS
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table RESTAURANT.USERS
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUseridIsNull() {
			addCriterion("USERID is null");
			return (Criteria) this;
		}

		public Criteria andUseridIsNotNull() {
			addCriterion("USERID is not null");
			return (Criteria) this;
		}

		public Criteria andUseridEqualTo(String value) {
			addCriterion("USERID =", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotEqualTo(String value) {
			addCriterion("USERID <>", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThan(String value) {
			addCriterion("USERID >", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThanOrEqualTo(String value) {
			addCriterion("USERID >=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThan(String value) {
			addCriterion("USERID <", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThanOrEqualTo(String value) {
			addCriterion("USERID <=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLike(String value) {
			addCriterion("USERID like", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotLike(String value) {
			addCriterion("USERID not like", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridIn(List<String> values) {
			addCriterion("USERID in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotIn(List<String> values) {
			addCriterion("USERID not in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridBetween(String value1, String value2) {
			addCriterion("USERID between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotBetween(String value1, String value2) {
			addCriterion("USERID not between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNull() {
			addCriterion("USERNAME is null");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNotNull() {
			addCriterion("USERNAME is not null");
			return (Criteria) this;
		}

		public Criteria andUsernameEqualTo(String value) {
			addCriterion("USERNAME =", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotEqualTo(String value) {
			addCriterion("USERNAME <>", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThan(String value) {
			addCriterion("USERNAME >", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("USERNAME >=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThan(String value) {
			addCriterion("USERNAME <", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThanOrEqualTo(String value) {
			addCriterion("USERNAME <=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLike(String value) {
			addCriterion("USERNAME like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotLike(String value) {
			addCriterion("USERNAME not like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameIn(List<String> values) {
			addCriterion("USERNAME in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotIn(List<String> values) {
			addCriterion("USERNAME not in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameBetween(String value1, String value2) {
			addCriterion("USERNAME between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotBetween(String value1, String value2) {
			addCriterion("USERNAME not between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("PASSWORD is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("PASSWORD is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("PASSWORD =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("PASSWORD <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("PASSWORD >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("PASSWORD >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("PASSWORD <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("PASSWORD <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("PASSWORD like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("PASSWORD not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("PASSWORD in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("PASSWORD not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("PASSWORD between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("PASSWORD not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andTelphoneIsNull() {
			addCriterion("TELPHONE is null");
			return (Criteria) this;
		}

		public Criteria andTelphoneIsNotNull() {
			addCriterion("TELPHONE is not null");
			return (Criteria) this;
		}

		public Criteria andTelphoneEqualTo(String value) {
			addCriterion("TELPHONE =", value, "telphone");
			return (Criteria) this;
		}

		public Criteria andTelphoneNotEqualTo(String value) {
			addCriterion("TELPHONE <>", value, "telphone");
			return (Criteria) this;
		}

		public Criteria andTelphoneGreaterThan(String value) {
			addCriterion("TELPHONE >", value, "telphone");
			return (Criteria) this;
		}

		public Criteria andTelphoneGreaterThanOrEqualTo(String value) {
			addCriterion("TELPHONE >=", value, "telphone");
			return (Criteria) this;
		}

		public Criteria andTelphoneLessThan(String value) {
			addCriterion("TELPHONE <", value, "telphone");
			return (Criteria) this;
		}

		public Criteria andTelphoneLessThanOrEqualTo(String value) {
			addCriterion("TELPHONE <=", value, "telphone");
			return (Criteria) this;
		}

		public Criteria andTelphoneLike(String value) {
			addCriterion("TELPHONE like", value, "telphone");
			return (Criteria) this;
		}

		public Criteria andTelphoneNotLike(String value) {
			addCriterion("TELPHONE not like", value, "telphone");
			return (Criteria) this;
		}

		public Criteria andTelphoneIn(List<String> values) {
			addCriterion("TELPHONE in", values, "telphone");
			return (Criteria) this;
		}

		public Criteria andTelphoneNotIn(List<String> values) {
			addCriterion("TELPHONE not in", values, "telphone");
			return (Criteria) this;
		}

		public Criteria andTelphoneBetween(String value1, String value2) {
			addCriterion("TELPHONE between", value1, value2, "telphone");
			return (Criteria) this;
		}

		public Criteria andTelphoneNotBetween(String value1, String value2) {
			addCriterion("TELPHONE not between", value1, value2, "telphone");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("EMAIL is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("EMAIL is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("EMAIL =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("EMAIL <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("EMAIL >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("EMAIL >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("EMAIL <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("EMAIL <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("EMAIL like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("EMAIL not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("EMAIL in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("EMAIL not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("EMAIL between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("EMAIL not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andQqIsNull() {
			addCriterion("QQ is null");
			return (Criteria) this;
		}

		public Criteria andQqIsNotNull() {
			addCriterion("QQ is not null");
			return (Criteria) this;
		}

		public Criteria andQqEqualTo(String value) {
			addCriterion("QQ =", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqNotEqualTo(String value) {
			addCriterion("QQ <>", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqGreaterThan(String value) {
			addCriterion("QQ >", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqGreaterThanOrEqualTo(String value) {
			addCriterion("QQ >=", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqLessThan(String value) {
			addCriterion("QQ <", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqLessThanOrEqualTo(String value) {
			addCriterion("QQ <=", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqLike(String value) {
			addCriterion("QQ like", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqNotLike(String value) {
			addCriterion("QQ not like", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqIn(List<String> values) {
			addCriterion("QQ in", values, "qq");
			return (Criteria) this;
		}

		public Criteria andQqNotIn(List<String> values) {
			addCriterion("QQ not in", values, "qq");
			return (Criteria) this;
		}

		public Criteria andQqBetween(String value1, String value2) {
			addCriterion("QQ between", value1, value2, "qq");
			return (Criteria) this;
		}

		public Criteria andQqNotBetween(String value1, String value2) {
			addCriterion("QQ not between", value1, value2, "qq");
			return (Criteria) this;
		}

		public Criteria andWeixinIsNull() {
			addCriterion("WEIXIN is null");
			return (Criteria) this;
		}

		public Criteria andWeixinIsNotNull() {
			addCriterion("WEIXIN is not null");
			return (Criteria) this;
		}

		public Criteria andWeixinEqualTo(String value) {
			addCriterion("WEIXIN =", value, "weixin");
			return (Criteria) this;
		}

		public Criteria andWeixinNotEqualTo(String value) {
			addCriterion("WEIXIN <>", value, "weixin");
			return (Criteria) this;
		}

		public Criteria andWeixinGreaterThan(String value) {
			addCriterion("WEIXIN >", value, "weixin");
			return (Criteria) this;
		}

		public Criteria andWeixinGreaterThanOrEqualTo(String value) {
			addCriterion("WEIXIN >=", value, "weixin");
			return (Criteria) this;
		}

		public Criteria andWeixinLessThan(String value) {
			addCriterion("WEIXIN <", value, "weixin");
			return (Criteria) this;
		}

		public Criteria andWeixinLessThanOrEqualTo(String value) {
			addCriterion("WEIXIN <=", value, "weixin");
			return (Criteria) this;
		}

		public Criteria andWeixinLike(String value) {
			addCriterion("WEIXIN like", value, "weixin");
			return (Criteria) this;
		}

		public Criteria andWeixinNotLike(String value) {
			addCriterion("WEIXIN not like", value, "weixin");
			return (Criteria) this;
		}

		public Criteria andWeixinIn(List<String> values) {
			addCriterion("WEIXIN in", values, "weixin");
			return (Criteria) this;
		}

		public Criteria andWeixinNotIn(List<String> values) {
			addCriterion("WEIXIN not in", values, "weixin");
			return (Criteria) this;
		}

		public Criteria andWeixinBetween(String value1, String value2) {
			addCriterion("WEIXIN between", value1, value2, "weixin");
			return (Criteria) this;
		}

		public Criteria andWeixinNotBetween(String value1, String value2) {
			addCriterion("WEIXIN not between", value1, value2, "weixin");
			return (Criteria) this;
		}

		public Criteria andSexIsNull() {
			addCriterion("SEX is null");
			return (Criteria) this;
		}

		public Criteria andSexIsNotNull() {
			addCriterion("SEX is not null");
			return (Criteria) this;
		}

		public Criteria andSexEqualTo(String value) {
			addCriterion("SEX =", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotEqualTo(String value) {
			addCriterion("SEX <>", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexGreaterThan(String value) {
			addCriterion("SEX >", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexGreaterThanOrEqualTo(String value) {
			addCriterion("SEX >=", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLessThan(String value) {
			addCriterion("SEX <", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLessThanOrEqualTo(String value) {
			addCriterion("SEX <=", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLike(String value) {
			addCriterion("SEX like", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotLike(String value) {
			addCriterion("SEX not like", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexIn(List<String> values) {
			addCriterion("SEX in", values, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotIn(List<String> values) {
			addCriterion("SEX not in", values, "sex");
			return (Criteria) this;
		}

		public Criteria andSexBetween(String value1, String value2) {
			addCriterion("SEX between", value1, value2, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotBetween(String value1, String value2) {
			addCriterion("SEX not between", value1, value2, "sex");
			return (Criteria) this;
		}

		public Criteria andOccupationIsNull() {
			addCriterion("OCCUPATION is null");
			return (Criteria) this;
		}

		public Criteria andOccupationIsNotNull() {
			addCriterion("OCCUPATION is not null");
			return (Criteria) this;
		}

		public Criteria andOccupationEqualTo(String value) {
			addCriterion("OCCUPATION =", value, "occupation");
			return (Criteria) this;
		}

		public Criteria andOccupationNotEqualTo(String value) {
			addCriterion("OCCUPATION <>", value, "occupation");
			return (Criteria) this;
		}

		public Criteria andOccupationGreaterThan(String value) {
			addCriterion("OCCUPATION >", value, "occupation");
			return (Criteria) this;
		}

		public Criteria andOccupationGreaterThanOrEqualTo(String value) {
			addCriterion("OCCUPATION >=", value, "occupation");
			return (Criteria) this;
		}

		public Criteria andOccupationLessThan(String value) {
			addCriterion("OCCUPATION <", value, "occupation");
			return (Criteria) this;
		}

		public Criteria andOccupationLessThanOrEqualTo(String value) {
			addCriterion("OCCUPATION <=", value, "occupation");
			return (Criteria) this;
		}

		public Criteria andOccupationLike(String value) {
			addCriterion("OCCUPATION like", value, "occupation");
			return (Criteria) this;
		}

		public Criteria andOccupationNotLike(String value) {
			addCriterion("OCCUPATION not like", value, "occupation");
			return (Criteria) this;
		}

		public Criteria andOccupationIn(List<String> values) {
			addCriterion("OCCUPATION in", values, "occupation");
			return (Criteria) this;
		}

		public Criteria andOccupationNotIn(List<String> values) {
			addCriterion("OCCUPATION not in", values, "occupation");
			return (Criteria) this;
		}

		public Criteria andOccupationBetween(String value1, String value2) {
			addCriterion("OCCUPATION between", value1, value2, "occupation");
			return (Criteria) this;
		}

		public Criteria andOccupationNotBetween(String value1, String value2) {
			addCriterion("OCCUPATION not between", value1, value2, "occupation");
			return (Criteria) this;
		}

		public Criteria andAgeIsNull() {
			addCriterion("AGE is null");
			return (Criteria) this;
		}

		public Criteria andAgeIsNotNull() {
			addCriterion("AGE is not null");
			return (Criteria) this;
		}

		public Criteria andAgeEqualTo(String value) {
			addCriterion("AGE =", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeNotEqualTo(String value) {
			addCriterion("AGE <>", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeGreaterThan(String value) {
			addCriterion("AGE >", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeGreaterThanOrEqualTo(String value) {
			addCriterion("AGE >=", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeLessThan(String value) {
			addCriterion("AGE <", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeLessThanOrEqualTo(String value) {
			addCriterion("AGE <=", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeLike(String value) {
			addCriterion("AGE like", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeNotLike(String value) {
			addCriterion("AGE not like", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeIn(List<String> values) {
			addCriterion("AGE in", values, "age");
			return (Criteria) this;
		}

		public Criteria andAgeNotIn(List<String> values) {
			addCriterion("AGE not in", values, "age");
			return (Criteria) this;
		}

		public Criteria andAgeBetween(String value1, String value2) {
			addCriterion("AGE between", value1, value2, "age");
			return (Criteria) this;
		}

		public Criteria andAgeNotBetween(String value1, String value2) {
			addCriterion("AGE not between", value1, value2, "age");
			return (Criteria) this;
		}

		public Criteria andLogoIsNull() {
			addCriterion("LOGO is null");
			return (Criteria) this;
		}

		public Criteria andLogoIsNotNull() {
			addCriterion("LOGO is not null");
			return (Criteria) this;
		}

		public Criteria andLogoEqualTo(String value) {
			addCriterion("LOGO =", value, "logo");
			return (Criteria) this;
		}

		public Criteria andLogoNotEqualTo(String value) {
			addCriterion("LOGO <>", value, "logo");
			return (Criteria) this;
		}

		public Criteria andLogoGreaterThan(String value) {
			addCriterion("LOGO >", value, "logo");
			return (Criteria) this;
		}

		public Criteria andLogoGreaterThanOrEqualTo(String value) {
			addCriterion("LOGO >=", value, "logo");
			return (Criteria) this;
		}

		public Criteria andLogoLessThan(String value) {
			addCriterion("LOGO <", value, "logo");
			return (Criteria) this;
		}

		public Criteria andLogoLessThanOrEqualTo(String value) {
			addCriterion("LOGO <=", value, "logo");
			return (Criteria) this;
		}

		public Criteria andLogoLike(String value) {
			addCriterion("LOGO like", value, "logo");
			return (Criteria) this;
		}

		public Criteria andLogoNotLike(String value) {
			addCriterion("LOGO not like", value, "logo");
			return (Criteria) this;
		}

		public Criteria andLogoIn(List<String> values) {
			addCriterion("LOGO in", values, "logo");
			return (Criteria) this;
		}

		public Criteria andLogoNotIn(List<String> values) {
			addCriterion("LOGO not in", values, "logo");
			return (Criteria) this;
		}

		public Criteria andLogoBetween(String value1, String value2) {
			addCriterion("LOGO between", value1, value2, "logo");
			return (Criteria) this;
		}

		public Criteria andLogoNotBetween(String value1, String value2) {
			addCriterion("LOGO not between", value1, value2, "logo");
			return (Criteria) this;
		}

		public Criteria andStateIsNull() {
			addCriterion("STATE is null");
			return (Criteria) this;
		}

		public Criteria andStateIsNotNull() {
			addCriterion("STATE is not null");
			return (Criteria) this;
		}

		public Criteria andStateEqualTo(String value) {
			addCriterion("STATE =", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotEqualTo(String value) {
			addCriterion("STATE <>", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThan(String value) {
			addCriterion("STATE >", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThanOrEqualTo(String value) {
			addCriterion("STATE >=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThan(String value) {
			addCriterion("STATE <", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThanOrEqualTo(String value) {
			addCriterion("STATE <=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLike(String value) {
			addCriterion("STATE like", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotLike(String value) {
			addCriterion("STATE not like", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateIn(List<String> values) {
			addCriterion("STATE in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotIn(List<String> values) {
			addCriterion("STATE not in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateBetween(String value1, String value2) {
			addCriterion("STATE between", value1, value2, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotBetween(String value1, String value2) {
			addCriterion("STATE not between", value1, value2, "state");
			return (Criteria) this;
		}

		public Criteria andIsuseIsNull() {
			addCriterion("ISUSE is null");
			return (Criteria) this;
		}

		public Criteria andIsuseIsNotNull() {
			addCriterion("ISUSE is not null");
			return (Criteria) this;
		}

		public Criteria andIsuseEqualTo(String value) {
			addCriterion("ISUSE =", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseNotEqualTo(String value) {
			addCriterion("ISUSE <>", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseGreaterThan(String value) {
			addCriterion("ISUSE >", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseGreaterThanOrEqualTo(String value) {
			addCriterion("ISUSE >=", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseLessThan(String value) {
			addCriterion("ISUSE <", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseLessThanOrEqualTo(String value) {
			addCriterion("ISUSE <=", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseLike(String value) {
			addCriterion("ISUSE like", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseNotLike(String value) {
			addCriterion("ISUSE not like", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseIn(List<String> values) {
			addCriterion("ISUSE in", values, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseNotIn(List<String> values) {
			addCriterion("ISUSE not in", values, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseBetween(String value1, String value2) {
			addCriterion("ISUSE between", value1, value2, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseNotBetween(String value1, String value2) {
			addCriterion("ISUSE not between", value1, value2, "isuse");
			return (Criteria) this;
		}

		public Criteria andJgnmIsNull() {
			addCriterion("JGNM is null");
			return (Criteria) this;
		}

		public Criteria andJgnmIsNotNull() {
			addCriterion("JGNM is not null");
			return (Criteria) this;
		}

		public Criteria andJgnmEqualTo(String value) {
			addCriterion("JGNM =", value, "jgnm");
			return (Criteria) this;
		}

		public Criteria andJgnmNotEqualTo(String value) {
			addCriterion("JGNM <>", value, "jgnm");
			return (Criteria) this;
		}

		public Criteria andJgnmGreaterThan(String value) {
			addCriterion("JGNM >", value, "jgnm");
			return (Criteria) this;
		}

		public Criteria andJgnmGreaterThanOrEqualTo(String value) {
			addCriterion("JGNM >=", value, "jgnm");
			return (Criteria) this;
		}

		public Criteria andJgnmLessThan(String value) {
			addCriterion("JGNM <", value, "jgnm");
			return (Criteria) this;
		}

		public Criteria andJgnmLessThanOrEqualTo(String value) {
			addCriterion("JGNM <=", value, "jgnm");
			return (Criteria) this;
		}

		public Criteria andJgnmLike(String value) {
			addCriterion("JGNM like", value, "jgnm");
			return (Criteria) this;
		}

		public Criteria andJgnmNotLike(String value) {
			addCriterion("JGNM not like", value, "jgnm");
			return (Criteria) this;
		}

		public Criteria andJgnmIn(List<String> values) {
			addCriterion("JGNM in", values, "jgnm");
			return (Criteria) this;
		}

		public Criteria andJgnmNotIn(List<String> values) {
			addCriterion("JGNM not in", values, "jgnm");
			return (Criteria) this;
		}

		public Criteria andJgnmBetween(String value1, String value2) {
			addCriterion("JGNM between", value1, value2, "jgnm");
			return (Criteria) this;
		}

		public Criteria andJgnmNotBetween(String value1, String value2) {
			addCriterion("JGNM not between", value1, value2, "jgnm");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("TYPE is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(String value) {
			addCriterion("TYPE =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(String value) {
			addCriterion("TYPE <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(String value) {
			addCriterion("TYPE >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(String value) {
			addCriterion("TYPE >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(String value) {
			addCriterion("TYPE <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(String value) {
			addCriterion("TYPE <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLike(String value) {
			addCriterion("TYPE like", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotLike(String value) {
			addCriterion("TYPE not like", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<String> values) {
			addCriterion("TYPE in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<String> values) {
			addCriterion("TYPE not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(String value1, String value2) {
			addCriterion("TYPE between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(String value1, String value2) {
			addCriterion("TYPE not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("CREATE_DATE is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("CREATE_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_DATE =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_DATE <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterionForJDBCDate("CREATE_DATE >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_DATE >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterionForJDBCDate("CREATE_DATE <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_DATE <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterionForJDBCDate("CREATE_DATE in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("CREATE_DATE not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATE_DATE between", value1, value2,
					"createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATE_DATE not between", value1, value2,
					"createDate");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNull() {
			addCriterion("CREATE_USER is null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNotNull() {
			addCriterion("CREATE_USER is not null");
			return (Criteria) this;
		}

		public Criteria andCreateUserEqualTo(String value) {
			addCriterion("CREATE_USER =", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotEqualTo(String value) {
			addCriterion("CREATE_USER <>", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThan(String value) {
			addCriterion("CREATE_USER >", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
			addCriterion("CREATE_USER >=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThan(String value) {
			addCriterion("CREATE_USER <", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThanOrEqualTo(String value) {
			addCriterion("CREATE_USER <=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLike(String value) {
			addCriterion("CREATE_USER like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotLike(String value) {
			addCriterion("CREATE_USER not like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserIn(List<String> values) {
			addCriterion("CREATE_USER in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotIn(List<String> values) {
			addCriterion("CREATE_USER not in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserBetween(String value1, String value2) {
			addCriterion("CREATE_USER between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotBetween(String value1, String value2) {
			addCriterion("CREATE_USER not between", value1, value2,
					"createUser");
			return (Criteria) this;
		}

		public Criteria andAlterDateIsNull() {
			addCriterion("ALTER_DATE is null");
			return (Criteria) this;
		}

		public Criteria andAlterDateIsNotNull() {
			addCriterion("ALTER_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andAlterDateEqualTo(Date value) {
			addCriterionForJDBCDate("ALTER_DATE =", value, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("ALTER_DATE <>", value, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateGreaterThan(Date value) {
			addCriterionForJDBCDate("ALTER_DATE >", value, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ALTER_DATE >=", value, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateLessThan(Date value) {
			addCriterionForJDBCDate("ALTER_DATE <", value, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ALTER_DATE <=", value, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateIn(List<Date> values) {
			addCriterionForJDBCDate("ALTER_DATE in", values, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("ALTER_DATE not in", values, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ALTER_DATE between", value1, value2,
					"alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ALTER_DATE not between", value1, value2,
					"alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterUserIsNull() {
			addCriterion("ALTER_USER is null");
			return (Criteria) this;
		}

		public Criteria andAlterUserIsNotNull() {
			addCriterion("ALTER_USER is not null");
			return (Criteria) this;
		}

		public Criteria andAlterUserEqualTo(String value) {
			addCriterion("ALTER_USER =", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserNotEqualTo(String value) {
			addCriterion("ALTER_USER <>", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserGreaterThan(String value) {
			addCriterion("ALTER_USER >", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserGreaterThanOrEqualTo(String value) {
			addCriterion("ALTER_USER >=", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserLessThan(String value) {
			addCriterion("ALTER_USER <", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserLessThanOrEqualTo(String value) {
			addCriterion("ALTER_USER <=", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserLike(String value) {
			addCriterion("ALTER_USER like", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserNotLike(String value) {
			addCriterion("ALTER_USER not like", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserIn(List<String> values) {
			addCriterion("ALTER_USER in", values, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserNotIn(List<String> values) {
			addCriterion("ALTER_USER not in", values, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserBetween(String value1, String value2) {
			addCriterion("ALTER_USER between", value1, value2, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserNotBetween(String value1, String value2) {
			addCriterion("ALTER_USER not between", value1, value2, "alterUser");
			return (Criteria) this;
		}

		public Criteria andDomainIsNull() {
			addCriterion("DOMAIN is null");
			return (Criteria) this;
		}

		public Criteria andDomainIsNotNull() {
			addCriterion("DOMAIN is not null");
			return (Criteria) this;
		}

		public Criteria andDomainEqualTo(String value) {
			addCriterion("DOMAIN =", value, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainNotEqualTo(String value) {
			addCriterion("DOMAIN <>", value, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainGreaterThan(String value) {
			addCriterion("DOMAIN >", value, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainGreaterThanOrEqualTo(String value) {
			addCriterion("DOMAIN >=", value, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainLessThan(String value) {
			addCriterion("DOMAIN <", value, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainLessThanOrEqualTo(String value) {
			addCriterion("DOMAIN <=", value, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainLike(String value) {
			addCriterion("DOMAIN like", value, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainNotLike(String value) {
			addCriterion("DOMAIN not like", value, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainIn(List<String> values) {
			addCriterion("DOMAIN in", values, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainNotIn(List<String> values) {
			addCriterion("DOMAIN not in", values, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainBetween(String value1, String value2) {
			addCriterion("DOMAIN between", value1, value2, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainNotBetween(String value1, String value2) {
			addCriterion("DOMAIN not between", value1, value2, "domain");
			return (Criteria) this;
		}

		public Criteria andHomepageIsNull() {
			addCriterion("HOMEPAGE is null");
			return (Criteria) this;
		}

		public Criteria andHomepageIsNotNull() {
			addCriterion("HOMEPAGE is not null");
			return (Criteria) this;
		}

		public Criteria andHomepageEqualTo(String value) {
			addCriterion("HOMEPAGE =", value, "homepage");
			return (Criteria) this;
		}

		public Criteria andHomepageNotEqualTo(String value) {
			addCriterion("HOMEPAGE <>", value, "homepage");
			return (Criteria) this;
		}

		public Criteria andHomepageGreaterThan(String value) {
			addCriterion("HOMEPAGE >", value, "homepage");
			return (Criteria) this;
		}

		public Criteria andHomepageGreaterThanOrEqualTo(String value) {
			addCriterion("HOMEPAGE >=", value, "homepage");
			return (Criteria) this;
		}

		public Criteria andHomepageLessThan(String value) {
			addCriterion("HOMEPAGE <", value, "homepage");
			return (Criteria) this;
		}

		public Criteria andHomepageLessThanOrEqualTo(String value) {
			addCriterion("HOMEPAGE <=", value, "homepage");
			return (Criteria) this;
		}

		public Criteria andHomepageLike(String value) {
			addCriterion("HOMEPAGE like", value, "homepage");
			return (Criteria) this;
		}

		public Criteria andHomepageNotLike(String value) {
			addCriterion("HOMEPAGE not like", value, "homepage");
			return (Criteria) this;
		}

		public Criteria andHomepageIn(List<String> values) {
			addCriterion("HOMEPAGE in", values, "homepage");
			return (Criteria) this;
		}

		public Criteria andHomepageNotIn(List<String> values) {
			addCriterion("HOMEPAGE not in", values, "homepage");
			return (Criteria) this;
		}

		public Criteria andHomepageBetween(String value1, String value2) {
			addCriterion("HOMEPAGE between", value1, value2, "homepage");
			return (Criteria) this;
		}

		public Criteria andHomepageNotBetween(String value1, String value2) {
			addCriterion("HOMEPAGE not between", value1, value2, "homepage");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table RESTAURANT.USERS
	 * @mbggenerated  Thu Nov 26 13:38:42 CAT 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table users
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 26 10:37:30 CAT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}