package dao.mybatis.model;

import java.util.Date;

public class Vip {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.VIP.ID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.VIP.CUSTOMERID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String customerid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.VIP.BOSSID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String bossid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.VIP.ISUSE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String isuse;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.VIP.SCORE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String score;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.VIP.CREATE_DATE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.VIP.CREATE_USER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.VIP.ALTER_DATE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private Date alterDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RESTAURANT.VIP.ALTER_USER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	private String alterUser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.VIP.ID
	 * @return  the value of RESTAURANT.VIP.ID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.VIP.ID
	 * @param id  the value for RESTAURANT.VIP.ID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.VIP.CUSTOMERID
	 * @return  the value of RESTAURANT.VIP.CUSTOMERID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getCustomerid() {
		return customerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.VIP.CUSTOMERID
	 * @param customerid  the value for RESTAURANT.VIP.CUSTOMERID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setCustomerid(String customerid) {
		this.customerid = customerid == null ? null : customerid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.VIP.BOSSID
	 * @return  the value of RESTAURANT.VIP.BOSSID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getBossid() {
		return bossid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.VIP.BOSSID
	 * @param bossid  the value for RESTAURANT.VIP.BOSSID
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setBossid(String bossid) {
		this.bossid = bossid == null ? null : bossid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.VIP.ISUSE
	 * @return  the value of RESTAURANT.VIP.ISUSE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getIsuse() {
		return isuse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.VIP.ISUSE
	 * @param isuse  the value for RESTAURANT.VIP.ISUSE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setIsuse(String isuse) {
		this.isuse = isuse == null ? null : isuse.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.VIP.SCORE
	 * @return  the value of RESTAURANT.VIP.SCORE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.VIP.SCORE
	 * @param score  the value for RESTAURANT.VIP.SCORE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setScore(String score) {
		this.score = score == null ? null : score.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.VIP.CREATE_DATE
	 * @return  the value of RESTAURANT.VIP.CREATE_DATE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.VIP.CREATE_DATE
	 * @param createDate  the value for RESTAURANT.VIP.CREATE_DATE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.VIP.CREATE_USER
	 * @return  the value of RESTAURANT.VIP.CREATE_USER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.VIP.CREATE_USER
	 * @param createUser  the value for RESTAURANT.VIP.CREATE_USER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser == null ? null : createUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.VIP.ALTER_DATE
	 * @return  the value of RESTAURANT.VIP.ALTER_DATE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public Date getAlterDate() {
		return alterDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.VIP.ALTER_DATE
	 * @param alterDate  the value for RESTAURANT.VIP.ALTER_DATE
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setAlterDate(Date alterDate) {
		this.alterDate = alterDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RESTAURANT.VIP.ALTER_USER
	 * @return  the value of RESTAURANT.VIP.ALTER_USER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getAlterUser() {
		return alterUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RESTAURANT.VIP.ALTER_USER
	 * @param alterUser  the value for RESTAURANT.VIP.ALTER_USER
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setAlterUser(String alterUser) {
		this.alterUser = alterUser == null ? null : alterUser.trim();
	}
}