package dao.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class VipExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RESTAURANT.VIP
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RESTAURANT.VIP
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RESTAURANT.VIP
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.VIP
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public VipExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.VIP
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.VIP
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.VIP
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.VIP
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.VIP
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.VIP
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.VIP
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.VIP
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.VIP
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RESTAURANT.VIP
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table RESTAURANT.VIP
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCustomeridIsNull() {
			addCriterion("CUSTOMERID is null");
			return (Criteria) this;
		}

		public Criteria andCustomeridIsNotNull() {
			addCriterion("CUSTOMERID is not null");
			return (Criteria) this;
		}

		public Criteria andCustomeridEqualTo(String value) {
			addCriterion("CUSTOMERID =", value, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridNotEqualTo(String value) {
			addCriterion("CUSTOMERID <>", value, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridGreaterThan(String value) {
			addCriterion("CUSTOMERID >", value, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridGreaterThanOrEqualTo(String value) {
			addCriterion("CUSTOMERID >=", value, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridLessThan(String value) {
			addCriterion("CUSTOMERID <", value, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridLessThanOrEqualTo(String value) {
			addCriterion("CUSTOMERID <=", value, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridLike(String value) {
			addCriterion("CUSTOMERID like", value, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridNotLike(String value) {
			addCriterion("CUSTOMERID not like", value, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridIn(List<String> values) {
			addCriterion("CUSTOMERID in", values, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridNotIn(List<String> values) {
			addCriterion("CUSTOMERID not in", values, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridBetween(String value1, String value2) {
			addCriterion("CUSTOMERID between", value1, value2, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridNotBetween(String value1, String value2) {
			addCriterion("CUSTOMERID not between", value1, value2, "customerid");
			return (Criteria) this;
		}

		public Criteria andBossidIsNull() {
			addCriterion("BOSSID is null");
			return (Criteria) this;
		}

		public Criteria andBossidIsNotNull() {
			addCriterion("BOSSID is not null");
			return (Criteria) this;
		}

		public Criteria andBossidEqualTo(String value) {
			addCriterion("BOSSID =", value, "bossid");
			return (Criteria) this;
		}

		public Criteria andBossidNotEqualTo(String value) {
			addCriterion("BOSSID <>", value, "bossid");
			return (Criteria) this;
		}

		public Criteria andBossidGreaterThan(String value) {
			addCriterion("BOSSID >", value, "bossid");
			return (Criteria) this;
		}

		public Criteria andBossidGreaterThanOrEqualTo(String value) {
			addCriterion("BOSSID >=", value, "bossid");
			return (Criteria) this;
		}

		public Criteria andBossidLessThan(String value) {
			addCriterion("BOSSID <", value, "bossid");
			return (Criteria) this;
		}

		public Criteria andBossidLessThanOrEqualTo(String value) {
			addCriterion("BOSSID <=", value, "bossid");
			return (Criteria) this;
		}

		public Criteria andBossidLike(String value) {
			addCriterion("BOSSID like", value, "bossid");
			return (Criteria) this;
		}

		public Criteria andBossidNotLike(String value) {
			addCriterion("BOSSID not like", value, "bossid");
			return (Criteria) this;
		}

		public Criteria andBossidIn(List<String> values) {
			addCriterion("BOSSID in", values, "bossid");
			return (Criteria) this;
		}

		public Criteria andBossidNotIn(List<String> values) {
			addCriterion("BOSSID not in", values, "bossid");
			return (Criteria) this;
		}

		public Criteria andBossidBetween(String value1, String value2) {
			addCriterion("BOSSID between", value1, value2, "bossid");
			return (Criteria) this;
		}

		public Criteria andBossidNotBetween(String value1, String value2) {
			addCriterion("BOSSID not between", value1, value2, "bossid");
			return (Criteria) this;
		}

		public Criteria andIsuseIsNull() {
			addCriterion("ISUSE is null");
			return (Criteria) this;
		}

		public Criteria andIsuseIsNotNull() {
			addCriterion("ISUSE is not null");
			return (Criteria) this;
		}

		public Criteria andIsuseEqualTo(String value) {
			addCriterion("ISUSE =", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseNotEqualTo(String value) {
			addCriterion("ISUSE <>", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseGreaterThan(String value) {
			addCriterion("ISUSE >", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseGreaterThanOrEqualTo(String value) {
			addCriterion("ISUSE >=", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseLessThan(String value) {
			addCriterion("ISUSE <", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseLessThanOrEqualTo(String value) {
			addCriterion("ISUSE <=", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseLike(String value) {
			addCriterion("ISUSE like", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseNotLike(String value) {
			addCriterion("ISUSE not like", value, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseIn(List<String> values) {
			addCriterion("ISUSE in", values, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseNotIn(List<String> values) {
			addCriterion("ISUSE not in", values, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseBetween(String value1, String value2) {
			addCriterion("ISUSE between", value1, value2, "isuse");
			return (Criteria) this;
		}

		public Criteria andIsuseNotBetween(String value1, String value2) {
			addCriterion("ISUSE not between", value1, value2, "isuse");
			return (Criteria) this;
		}

		public Criteria andScoreIsNull() {
			addCriterion("SCORE is null");
			return (Criteria) this;
		}

		public Criteria andScoreIsNotNull() {
			addCriterion("SCORE is not null");
			return (Criteria) this;
		}

		public Criteria andScoreEqualTo(String value) {
			addCriterion("SCORE =", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotEqualTo(String value) {
			addCriterion("SCORE <>", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreGreaterThan(String value) {
			addCriterion("SCORE >", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreGreaterThanOrEqualTo(String value) {
			addCriterion("SCORE >=", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLessThan(String value) {
			addCriterion("SCORE <", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLessThanOrEqualTo(String value) {
			addCriterion("SCORE <=", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLike(String value) {
			addCriterion("SCORE like", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotLike(String value) {
			addCriterion("SCORE not like", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreIn(List<String> values) {
			addCriterion("SCORE in", values, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotIn(List<String> values) {
			addCriterion("SCORE not in", values, "score");
			return (Criteria) this;
		}

		public Criteria andScoreBetween(String value1, String value2) {
			addCriterion("SCORE between", value1, value2, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotBetween(String value1, String value2) {
			addCriterion("SCORE not between", value1, value2, "score");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("CREATE_DATE is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("CREATE_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_DATE =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_DATE <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterionForJDBCDate("CREATE_DATE >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_DATE >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterionForJDBCDate("CREATE_DATE <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_DATE <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterionForJDBCDate("CREATE_DATE in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("CREATE_DATE not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATE_DATE between", value1, value2,
					"createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATE_DATE not between", value1, value2,
					"createDate");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNull() {
			addCriterion("CREATE_USER is null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNotNull() {
			addCriterion("CREATE_USER is not null");
			return (Criteria) this;
		}

		public Criteria andCreateUserEqualTo(String value) {
			addCriterion("CREATE_USER =", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotEqualTo(String value) {
			addCriterion("CREATE_USER <>", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThan(String value) {
			addCriterion("CREATE_USER >", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
			addCriterion("CREATE_USER >=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThan(String value) {
			addCriterion("CREATE_USER <", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThanOrEqualTo(String value) {
			addCriterion("CREATE_USER <=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLike(String value) {
			addCriterion("CREATE_USER like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotLike(String value) {
			addCriterion("CREATE_USER not like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserIn(List<String> values) {
			addCriterion("CREATE_USER in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotIn(List<String> values) {
			addCriterion("CREATE_USER not in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserBetween(String value1, String value2) {
			addCriterion("CREATE_USER between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotBetween(String value1, String value2) {
			addCriterion("CREATE_USER not between", value1, value2,
					"createUser");
			return (Criteria) this;
		}

		public Criteria andAlterDateIsNull() {
			addCriterion("ALTER_DATE is null");
			return (Criteria) this;
		}

		public Criteria andAlterDateIsNotNull() {
			addCriterion("ALTER_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andAlterDateEqualTo(Date value) {
			addCriterionForJDBCDate("ALTER_DATE =", value, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("ALTER_DATE <>", value, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateGreaterThan(Date value) {
			addCriterionForJDBCDate("ALTER_DATE >", value, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ALTER_DATE >=", value, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateLessThan(Date value) {
			addCriterionForJDBCDate("ALTER_DATE <", value, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ALTER_DATE <=", value, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateIn(List<Date> values) {
			addCriterionForJDBCDate("ALTER_DATE in", values, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("ALTER_DATE not in", values, "alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ALTER_DATE between", value1, value2,
					"alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ALTER_DATE not between", value1, value2,
					"alterDate");
			return (Criteria) this;
		}

		public Criteria andAlterUserIsNull() {
			addCriterion("ALTER_USER is null");
			return (Criteria) this;
		}

		public Criteria andAlterUserIsNotNull() {
			addCriterion("ALTER_USER is not null");
			return (Criteria) this;
		}

		public Criteria andAlterUserEqualTo(String value) {
			addCriterion("ALTER_USER =", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserNotEqualTo(String value) {
			addCriterion("ALTER_USER <>", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserGreaterThan(String value) {
			addCriterion("ALTER_USER >", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserGreaterThanOrEqualTo(String value) {
			addCriterion("ALTER_USER >=", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserLessThan(String value) {
			addCriterion("ALTER_USER <", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserLessThanOrEqualTo(String value) {
			addCriterion("ALTER_USER <=", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserLike(String value) {
			addCriterion("ALTER_USER like", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserNotLike(String value) {
			addCriterion("ALTER_USER not like", value, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserIn(List<String> values) {
			addCriterion("ALTER_USER in", values, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserNotIn(List<String> values) {
			addCriterion("ALTER_USER not in", values, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserBetween(String value1, String value2) {
			addCriterion("ALTER_USER between", value1, value2, "alterUser");
			return (Criteria) this;
		}

		public Criteria andAlterUserNotBetween(String value1, String value2) {
			addCriterion("ALTER_USER not between", value1, value2, "alterUser");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table RESTAURANT.VIP
	 * @mbggenerated  Thu Nov 26 13:19:00 CAT 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vip
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 26 10:37:30 CAT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}